// Generated by tools/build-earth.mjs — do not edit by hand.
//
// Shape of the companion earth.bin: three byte planes, one byte per cell in
// grid order, sampled from NASA-derived equirectangular rasters (land mask,
// topography, natural-colour imagery) shipped with the three-globe package.
export const EARTH = {
  frequency: 107,
  cells: 114492,
  /** Byte planes in order, one byte per cell. */
  planes: ['land', 'elevation', 'green'],
};
