// The order of battle of 1 September 1939, as formations rather than a field.
//
// This file is data. Nothing in it knows how a hex is chosen; the generator in
// `deploy.js` reads it and does the placing, so a figure can be corrected here
// without touching a line of code. Every row carries a source note for the same
// reason: the numbers are approximations to commonly cited ranges, they will be
// wrong somewhere, and whoever fixes one should be able to see what it was.
//
// The point of the file is that armies of 1939 were lumpy. A handful of cells
// held nearly everything; most held nothing military at all; and tanks and
// aircraft existed only as whole formations parked in particular places. A
// model that spreads a nation's strength over its population produces the
// opposite of all three, and produced — before this file existed — a tank
// squadron and a bomber group in every rural district of Brandenburg.
//
// ---------------------------------------------------------------- the schema
//
// A FORMATION is:
//
//   id         unique, and used in the tests
//   name       what a panel calls it. Optional: without one the name is taken
//              from the first clause of the source note, which reads well for
//              "3rd Army (Kuchler), East Prussia" and badly for a sentence.
//   nation     which power's pool it comes out of
//   type       what it is, which decides how it is placed:
//
//                field      an army, corps or division in the line
//                armor      a tank or mechanised formation — placed whole, in
//                           one cell, never spread
//                air        a wing or group — one cell, and that cell becomes
//                           an airbase; aircraft appear nowhere else
//                fortress   static frontier troops, pinned to the front line
//                depot      replacement, training and cadre — in home towns,
//                           and NOT counted as field strength
//                security   rear-area and occupation troops, thin over ground
//                aa         anti-aircraft, over industry and cities, never
//                           on a front
//
//   echelon    what it would be called: 'army', 'corps', 'division', 'command'
//   strength   { infantry, tanks, artillery, fighters, bombers }
//   quality    0-1, how well found and trained it is. Not used for placement;
//              it is here so a Chinese division and a German one are not the
//              same counter when the fighting arrives.
//   mobility   0-1, how fast it can move off its ground.
//   theater    a label for grouping, not a rule.
//   zone       which deployment zone it belongs in — see ZONES below
//   sites      or, instead of a zone, explicit places: [[lat, lon, weight?]]
//   source     where the figure came from, in a few words
//
// A ZONE is a piece of ground with a front and a doctrine:
//
//   boxes      [west, south, east, north] rectangles the zone covers
//   facing     the countries or powers its front looks at. Distance to the
//              nearest of them, in hexes, is what the doctrine profile shapes.
//   doctrine   schwerpunkt | cordon | fortified_line | defense_in_depth |
//              imperial_nodes | corridor_occupation | skeleton
//   colonial   true where roads and railways are not to be assumed

export const DOCTRINES = [
  'schwerpunkt',
  'cordon',
  'fortified_line',
  'defense_in_depth',
  'imperial_nodes',
  'corridor_occupation',
  'skeleton',
];

export const FORMATION_TYPES = [
  'field',
  'armor',
  'air',
  'fortress',
  'depot',
  'security',
  'aa',
];

/** Types whose men are field strength. Depots, security and flak are not. */
export const FIELD_TYPES = new Set(['field', 'armor', 'fortress']);

export const ZONES = {
  // ======================== GERMANY ======================================
  // Two army groups east and one west, and the whole argument of the campaign
  // is in the ratio between them: sixty divisions and every tank against
  // Poland, forty second-wave divisions and no tanks at all on the Rhine.
  'de-east-prussia': {
    nation: 'germany',
    name: 'East Prussia',
    boxes: [[19.3, 53.9, 23.0, 55.9]],
    facing: ['Poland'],
    doctrine: 'schwerpunkt',
  },
  'de-pomerania': {
    nation: 'germany',
    name: 'Pomerania and the Corridor',
    boxes: [[13.6, 52.8, 17.6, 54.8]],
    facing: ['Poland'],
    doctrine: 'schwerpunkt',
  },
  'de-silesia': {
    nation: 'germany',
    name: 'Silesia',
    boxes: [[15.1, 49.6, 19.0, 52.0]],
    facing: ['Poland'],
    doctrine: 'schwerpunkt',
  },
  'de-moravia': {
    // The 14th Army stood on Slovak and Moravian ground, which is not German
    // ground. A generator keyed on nationality puts these divisions in the
    // wrong country; a zone keyed on a rectangle does not.
    nation: 'germany',
    name: 'Moravia and Slovakia',
    boxes: [[16.6, 47.9, 22.4, 50.2]],
    facing: ['Poland'],
    doctrine: 'schwerpunkt',
    staging: true,
  },
  'de-westwall': {
    nation: 'germany',
    name: 'The West Wall',
    // The frontier belt from Basel to the lower Rhine. It is the depth cut
    // in the doctrine profile that keeps the Ruhr out of it, not the box:
    // Essen is four hexes back along German ground and had flak over it
    // rather than divisions in it.
    boxes: [[5.8, 47.4, 9.0, 51.9]],
    facing: ['France'],
    doctrine: 'fortified_line',
  },
  'de-interior': {
    nation: 'germany',
    name: 'The Reich',
    boxes: [[5.8, 47.2, 16.3, 55.1]],
    doctrine: 'skeleton',
  },

  // ========================= POLAND ======================================
  // The cordon. Six armies strung along a frontier of two thousand kilometres
  // including the western salient that could not be held, and one reserve army
  // too far back to matter. This is the famous error and it is encoded as one:
  // a rational deployment behind the Vistula and the San would score quite
  // differently, and the test suite asserts that Poland is flatter than
  // Germany rather than better.
  'pl-corridor': {
    nation: 'neutral',
    name: 'The Corridor',
    boxes: [[16.8, 52.6, 20.0, 54.9]],
    facing: ['germany'],
    doctrine: 'cordon',
  },
  'pl-west': {
    nation: 'neutral',
    name: 'The western salient',
    boxes: [[16.3, 51.0, 19.6, 53.0]],
    facing: ['germany'],
    doctrine: 'cordon',
  },
  'pl-south': {
    nation: 'neutral',
    name: 'Silesia and the Carpathians',
    boxes: [[18.0, 49.0, 23.0, 51.2]],
    facing: ['germany', 'Slovakia'],
    doctrine: 'cordon',
  },
  'pl-reserve': {
    nation: 'neutral',
    name: 'The central reserve',
    boxes: [[19.0, 50.6, 22.5, 52.6]],
    doctrine: 'skeleton',
  },

  // ========================= FRANCE ======================================
  'fr-maginot': {
    nation: 'france',
    name: 'The Maginot Line',
    // Switzerland to Longuyon, and no further: the line stops where the
    // Belgian frontier begins, which is the gap the war came through.
    boxes: [[4.6, 47.3, 8.4, 49.7]],
    facing: ['germany'],
    doctrine: 'fortified_line',
  },
  'fr-northeast': {
    nation: 'france',
    name: 'The north-east',
    boxes: [[4.0, 48.6, 8.3, 50.4]],
    facing: ['germany'],
    doctrine: 'fortified_line',
  },
  'fr-north': {
    // No line at all here, so the mobile armies stand in it: 1st, 7th and 9th,
    // the best in France, waiting to advance into Belgium.
    nation: 'france',
    name: 'The Belgian frontier',
    boxes: [[1.6, 49.4, 5.2, 51.1]],
    facing: ['Belgium'],
    doctrine: 'defense_in_depth',
  },
  'fr-alps': {
    nation: 'france',
    name: 'The Army of the Alps',
    boxes: [[5.5, 43.4, 7.9, 46.4]],
    facing: ['italy'],
    doctrine: 'fortified_line',
  },
  'fr-interior': {
    nation: 'france',
    name: 'The interior',
    boxes: [[-5.2, 42.3, 8.3, 51.1]],
    doctrine: 'skeleton',
  },
  'fr-africa': {
    nation: 'france',
    name: 'North Africa',
    boxes: [[-13.3, 27.6, 11.6, 37.5]],
    doctrine: 'imperial_nodes',
    colonial: true,
  },
  'fr-levant': {
    nation: 'france',
    name: 'The Levant',
    boxes: [[35.0, 32.2, 42.4, 37.1]],
    doctrine: 'imperial_nodes',
    colonial: true,
  },
  'fr-indochina': {
    nation: 'france',
    name: 'Indochina',
    boxes: [[100.0, 8.4, 109.6, 23.4]],
    doctrine: 'imperial_nodes',
    colonial: true,
  },

  // ==================== THE UNITED KINGDOM ================================
  // Almost nothing on the ground at home: four divisions still embarking, and
  // a country whose real defence is a radar chain, sixty fighter squadrons and
  // the heaviest anti-aircraft belt in the world.
  'uk-home': {
    nation: 'uk',
    name: 'Home Forces',
    boxes: [[-8.3, 49.8, 2.1, 59.5]],
    doctrine: 'skeleton',
  },
  'uk-india': {
    nation: 'uk',
    name: 'India',
    boxes: [[66.0, 6.5, 92.0, 36.5]],
    doctrine: 'imperial_nodes',
  },
  'uk-middle-east': {
    nation: 'uk',
    name: 'Middle East Command',
    boxes: [[21.8, 12.0, 48.8, 33.3]],
    doctrine: 'imperial_nodes',
    colonial: true,
  },
  'uk-far-east': {
    nation: 'uk',
    name: 'The Far East',
    boxes: [[92.0, -1.0, 120.0, 28.6]],
    doctrine: 'imperial_nodes',
    colonial: true,
  },
  'uk-africa': {
    nation: 'uk',
    name: 'The African garrisons',
    boxes: [[-17.6, -35.0, 42.0, 14.0]],
    doctrine: 'imperial_nodes',
    colonial: true,
  },
  'uk-dominions': {
    nation: 'uk',
    name: 'The Dominions',
    boxes: [[-141.0, -47.5, -52.0, 83.0], [112.5, -47.5, 179.9, -10.0]],
    doctrine: 'skeleton',
  },

  // ===================== THE SOVIET UNION =================================
  // Three concentrations and an empty middle. The western districts are
  // massing for the 17 September entry into Poland; the Far East is fighting
  // at Khalkhin Gol as the war in Europe begins; Leningrad is building towards
  // a frontier it will attack in November. Everything between is cadre.
  'su-belorussia': {
    nation: 'ussr',
    name: 'Belorussian Special Military District',
    boxes: [[26.0, 51.5, 32.5, 56.5]],
    facing: ['Poland'],
    doctrine: 'defense_in_depth',
  },
  'su-kiev': {
    nation: 'ussr',
    name: 'Kiev Special Military District',
    boxes: [[25.5, 47.5, 33.0, 52.0]],
    facing: ['Poland', 'Romania'],
    doctrine: 'defense_in_depth',
  },
  'su-leningrad': {
    nation: 'ussr',
    name: 'Leningrad Military District',
    boxes: [[28.0, 58.5, 34.0, 63.0]],
    facing: ['Finland'],
    doctrine: 'defense_in_depth',
  },
  'su-far-east': {
    nation: 'ussr',
    name: 'The Far Eastern Front',
    boxes: [[127.0, 42.0, 141.0, 51.0]],
    facing: ['Manchukuo'],
    doctrine: 'defense_in_depth',
  },
  'su-transbaikal': {
    nation: 'ussr',
    name: 'The Transbaikal Front',
    boxes: [[106.0, 48.0, 122.0, 54.0]],
    facing: ['japan'],
    doctrine: 'defense_in_depth',
  },
  'su-interior': {
    nation: 'ussr',
    name: 'The interior districts',
    boxes: [[19.0, 35.0, 190.0, 82.0]],
    doctrine: 'skeleton',
  },

  // ========================== ITALY ======================================
  'it-alps': {
    nation: 'italy',
    name: 'The 1st Army',
    boxes: [[6.6, 43.8, 9.0, 46.5]],
    facing: ['France'],
    doctrine: 'fortified_line',
  },
  'it-east': {
    nation: 'italy',
    name: 'The 2nd Army',
    boxes: [[12.4, 45.4, 14.0, 46.8]],
    facing: ['Yugoslavia'],
    doctrine: 'cordon',
  },
  'it-home': {
    nation: 'italy',
    name: 'The peninsula',
    boxes: [[7.0, 36.5, 18.6, 46.7]],
    doctrine: 'skeleton',
  },
  'it-libya': {
    nation: 'italy',
    name: 'Libya',
    boxes: [[9.3, 19.5, 25.2, 34.0]],
    doctrine: 'imperial_nodes',
    colonial: true,
  },
  'it-east-africa': {
    nation: 'italy',
    name: 'Italian East Africa',
    boxes: [[34.5, -1.7, 51.6, 18.1]],
    doctrine: 'imperial_nodes',
    colonial: true,
  },
  'it-albania': {
    nation: 'italy',
    name: 'Albania',
    boxes: [[19.2, 39.6, 21.1, 42.4]],
    doctrine: 'imperial_nodes',
  },

  // ========================== JAPAN ======================================
  // The army is on the mainland, and in China it holds cities, ports and the
  // railways between them. The countryside in between held no Japanese troops
  // at all, which is what corridor_occupation means: everything on the nodes,
  // nothing in the space.
  'jp-north-china': {
    nation: 'japan',
    name: 'North China Area Army',
    boxes: [[110.0, 32.0, 122.5, 41.5]],
    doctrine: 'corridor_occupation',
  },
  'jp-central-china': {
    nation: 'japan',
    name: 'Central China Expeditionary Army',
    boxes: [[113.2, 27.5, 122.5, 33.0]],
    doctrine: 'corridor_occupation',
  },
  'jp-south-china': {
    nation: 'japan',
    name: 'South China',
    boxes: [[108.5, 18.1, 117.5, 24.5]],
    doctrine: 'corridor_occupation',
  },
  'jp-manchuria': {
    nation: 'japan',
    name: 'The Kwantung Army',
    boxes: [[115.6, 38.7, 133.0, 53.4]],
    facing: ['ussr', 'Mongolia'],
    doctrine: 'defense_in_depth',
  },
  'jp-korea': {
    nation: 'japan',
    name: 'The Korea Army',
    boxes: [[124.2, 33.9, 130.8, 42.5]],
    doctrine: 'skeleton',
  },
  'jp-home': {
    nation: 'japan',
    name: 'The home islands',
    boxes: [[128.3, 30.0, 146.0, 45.8]],
    doctrine: 'skeleton',
  },

  // ========================== CHINA ======================================
  'cn-north-front': {
    nation: 'china',
    name: 'The northern war zones',
    boxes: [[104.0, 33.0, 114.0, 41.0]],
    facing: ['japan'],
    doctrine: 'cordon',
  },
  'cn-central-front': {
    nation: 'china',
    name: 'The central war zones',
    boxes: [[108.0, 26.0, 116.0, 33.5]],
    facing: ['japan'],
    doctrine: 'cordon',
  },
  'cn-south-front': {
    nation: 'china',
    name: 'The southern war zones',
    boxes: [[104.0, 21.0, 114.0, 27.0]],
    facing: ['japan'],
    doctrine: 'cordon',
  },
  'cn-rear': {
    nation: 'china',
    name: 'Sichuan and the rear',
    boxes: [[101.0, 26.0, 110.0, 34.0]],
    doctrine: 'skeleton',
  },
  'cn-shaanxi': {
    nation: 'china',
    name: 'The Eighth Route Army',
    boxes: [[106.0, 34.5, 114.0, 39.5]],
    doctrine: 'corridor_occupation',
  },

  // ===================== THE UNITED STATES ================================
  // Nineteenth in the world, and it looks it: a handful of posts holding
  // divisions at half strength, and an interior with nothing in it at all.
  'us-continental': {
    nation: 'usa',
    name: 'The continental army',
    boxes: [[-125.0, 24.4, -66.9, 49.0]],
    doctrine: 'skeleton',
  },
  'us-overseas': {
    nation: 'usa',
    name: 'The overseas departments',
    boxes: [[-180.0, -20.0, 180.0, 60.0]],
    doctrine: 'imperial_nodes',
  },

  // ====================== THE MINOR POWERS ================================
  // Pooled as Independent on the board, but each on its own frontier, because
  // that is where each of them actually stood.
  'be-frontier': {
    nation: 'neutral',
    name: 'The Belgian frontier',
    boxes: [[2.5, 49.5, 6.4, 51.6]],
    facing: ['germany'],
    doctrine: 'cordon',
  },
  'nl-frontier': {
    nation: 'neutral',
    name: 'The Dutch water line',
    boxes: [[3.3, 50.7, 7.3, 53.6]],
    facing: ['germany'],
    doctrine: 'cordon',
  },
  'fi-karelia': {
    nation: 'neutral',
    name: 'The Karelian Isthmus',
    boxes: [[24.0, 60.0, 31.6, 63.0]],
    facing: ['Soviet Union'],
    doctrine: 'fortified_line',
  },
  'ro-frontier': {
    nation: 'neutral',
    name: 'Bessarabia and the west',
    boxes: [[20.2, 43.6, 29.8, 48.3]],
    facing: ['Soviet Union', 'Hungary'],
    doctrine: 'cordon',
  },
  'hu-frontier': {
    nation: 'neutral',
    name: 'Hungary',
    boxes: [[17.2, 45.7, 22.9, 48.7]],
    doctrine: 'skeleton',
  },
  'yu-frontier': {
    nation: 'neutral',
    name: 'Yugoslavia',
    boxes: [[13.9, 40.8, 23.0, 46.9]],
    facing: ['italy'],
    doctrine: 'cordon',
  },
  'gr-frontier': {
    nation: 'neutral',
    name: 'Greece',
    boxes: [[19.3, 34.8, 28.3, 41.8]],
    facing: ['Albania'],
    doctrine: 'cordon',
  },
  'tr-thrace': {
    nation: 'neutral',
    name: 'Thrace and the Straits',
    boxes: [[25.5, 35.5, 44.9, 42.6]],
    doctrine: 'skeleton',
  },
  'es-home': {
    nation: 'neutral',
    name: 'Spain, demobilising',
    boxes: [[-10.0, 36.0, 3.3, 44.0]],
    doctrine: 'skeleton',
  },
  'se-home': {
    nation: 'neutral',
    name: 'Sweden',
    boxes: [[11.0, 55.2, 24.2, 69.1]],
    doctrine: 'skeleton',
  },
  'ch-redoubt': {
    nation: 'neutral',
    name: 'The Swiss redoubt',
    boxes: [[5.9, 45.8, 10.5, 47.9]],
    doctrine: 'cordon',
    facing: ['germany', 'italy', 'france'],
  },
};

export const FORMATIONS = [
  // ==================================================================== //
  //                              GERMANY                                 //
  // ==================================================================== //
  // East, ~1.5M men in sixty divisions, and every tank in the army.
  {
    id: 'de-3-army',
    nation: 'germany',
    type: 'field',
    echelon: 'army',
    theater: 'east',
    zone: 'de-east-prussia',
    strength: { infantry: 320000, artillery: 1100 },
    quality: 0.85,
    mobility: 0.4,
    source: '3rd Army (Küchler), East Prussia, ~11 divisions',
  },
  {
    id: 'de-4-army',
    nation: 'germany',
    type: 'field',
    echelon: 'army',
    theater: 'east',
    zone: 'de-pomerania',
    strength: { infantry: 230000, artillery: 850 },
    quality: 0.85,
    mobility: 0.4,
    source: '4th Army (Kluge), Pomerania, aimed across the Corridor',
  },
  {
    id: 'de-8-army',
    nation: 'germany',
    type: 'field',
    echelon: 'army',
    theater: 'east',
    zone: 'de-silesia',
    strength: { infantry: 180000, artillery: 700 },
    quality: 0.8,
    mobility: 0.4,
    source: '8th Army (Blaskowitz), northern Silesia, flank guard',
  },
  {
    id: 'de-10-army',
    nation: 'germany',
    type: 'field',
    echelon: 'army',
    theater: 'east',
    zone: 'de-silesia',
    strength: { infantry: 300000, artillery: 1400 },
    quality: 0.9,
    mobility: 0.55,
    source: '10th Army (Reichenau), the main effort, southern Silesia',
  },
  {
    id: 'de-14-army',
    nation: 'germany',
    type: 'field',
    echelon: 'army',
    theater: 'east',
    zone: 'de-moravia',
    strength: { infantry: 210000, artillery: 900 },
    quality: 0.85,
    mobility: 0.45,
    source: '14th Army (List), staged in Moravia and Slovakia',
  },
  {
    id: 'de-east-reserve',
    name: 'OKH eastern reserve',
    nation: 'germany',
    type: 'field',
    echelon: 'corps',
    theater: 'east',
    zone: 'de-silesia',
    strength: { infantry: 260000, artillery: 1050 },
    quality: 0.75,
    mobility: 0.35,
    source: 'OKH reserve behind the eastern front, second-wave divisions',
  },

  // The armour. Six panzer divisions, four light, one improvised, and the
  // independent battalions — about 3,200 tanks, none of them west of the Rhine.
  {
    id: 'de-1-panzer',
    nation: 'germany',
    type: 'armor',
    echelon: 'division',
    theater: 'east',
    zone: 'de-silesia',
    strength: { infantry: 13000, tanks: 310, artillery: 60 },
    quality: 0.95,
    mobility: 0.95,
    source: '1st Panzer Division, XVI Corps, 10th Army',
  },
  {
    id: 'de-4-panzer',
    nation: 'germany',
    type: 'armor',
    echelon: 'division',
    theater: 'east',
    zone: 'de-silesia',
    strength: { infantry: 12000, tanks: 340, artillery: 55 },
    quality: 0.95,
    mobility: 0.95,
    source: '4th Panzer Division, XVI Corps, 10th Army',
  },
  {
    id: 'de-2-panzer',
    nation: 'germany',
    type: 'armor',
    echelon: 'division',
    theater: 'east',
    zone: 'de-moravia',
    strength: { infantry: 12000, tanks: 300, artillery: 55 },
    quality: 0.95,
    mobility: 0.95,
    source: '2nd Panzer Division, XVIII Corps, 14th Army',
  },
  {
    id: 'de-5-panzer',
    nation: 'germany',
    type: 'armor',
    echelon: 'division',
    theater: 'east',
    zone: 'de-moravia',
    strength: { infantry: 12000, tanks: 320, artillery: 55 },
    quality: 0.95,
    mobility: 0.95,
    source: '5th Panzer Division, VIII Corps, 14th Army',
  },
  {
    id: 'de-3-panzer',
    nation: 'germany',
    type: 'armor',
    echelon: 'division',
    theater: 'east',
    zone: 'de-pomerania',
    strength: { infantry: 12000, tanks: 390, artillery: 55 },
    quality: 0.95,
    mobility: 0.95,
    source: '3rd Panzer Division, XIX Corps (Guderian), 4th Army',
  },
  {
    id: 'de-10-panzer',
    nation: 'germany',
    type: 'armor',
    echelon: 'division',
    theater: 'east',
    zone: 'de-east-prussia',
    strength: { infantry: 10000, tanks: 150, artillery: 40 },
    quality: 0.8,
    mobility: 0.9,
    source: '10th Panzer Division, forming, with 3rd Army',
  },
  {
    id: 'de-kempf',
    nation: 'germany',
    type: 'armor',
    echelon: 'division',
    theater: 'east',
    zone: 'de-east-prussia',
    strength: { infantry: 9000, tanks: 160, artillery: 35 },
    quality: 0.8,
    mobility: 0.9,
    source: 'Panzer Division Kempf, East Prussia',
  },
  {
    id: 'de-1-light',
    nation: 'germany',
    type: 'armor',
    echelon: 'division',
    theater: 'east',
    zone: 'de-silesia',
    strength: { infantry: 11000, tanks: 220, artillery: 40 },
    quality: 0.85,
    mobility: 0.9,
    source: '1st Light Division, 10th Army',
  },
  {
    id: 'de-2-light',
    nation: 'germany',
    type: 'armor',
    echelon: 'division',
    theater: 'east',
    zone: 'de-moravia',
    strength: { infantry: 10000, tanks: 190, artillery: 40 },
    quality: 0.8,
    mobility: 0.9,
    source: '2nd Light Division, 14th Army',
  },
  {
    id: 'de-3-light',
    nation: 'germany',
    type: 'armor',
    echelon: 'division',
    theater: 'east',
    zone: 'de-moravia',
    strength: { infantry: 10000, tanks: 200, artillery: 40 },
    quality: 0.8,
    mobility: 0.9,
    source: '3rd Light Division, 14th Army',
  },
  {
    id: 'de-4-light',
    nation: 'germany',
    type: 'armor',
    echelon: 'division',
    theater: 'east',
    zone: 'de-silesia',
    strength: { infantry: 10000, tanks: 180, artillery: 40 },
    quality: 0.8,
    mobility: 0.9,
    source: '4th Light Division, 14th Army',
  },
  {
    id: 'de-panzer-abt-east',
    name: 'Panzer-Abteilungen, XIX Corps',
    nation: 'germany',
    type: 'armor',
    echelon: 'corps',
    theater: 'east',
    zone: 'de-pomerania',
    strength: { infantry: 8000, tanks: 320, artillery: 30 },
    quality: 0.75,
    mobility: 0.85,
    source: 'independent Panzer-Abteilungen with XIX Corps',
  },
  {
    id: 'de-motorised',
    nation: 'germany',
    type: 'armor',
    echelon: 'corps',
    theater: 'east',
    zone: 'de-silesia',
    strength: { infantry: 44000, tanks: 120, artillery: 180 },
    quality: 0.9,
    mobility: 0.9,
    source: '2nd, 13th, 20th and 29th Motorised Divisions — lorried, few tanks',
  },
  {
    id: 'de-ss-motorised',
    name: 'SS-VT and Panzer-Lehr',
    nation: 'germany',
    type: 'armor',
    echelon: 'division',
    theater: 'east',
    zone: 'de-silesia',
    strength: { infantry: 18000, tanks: 190, artillery: 60 },
    quality: 0.85,
    mobility: 0.9,
    source: 'SS-VT regiments and Panzer-Lehr detachments attached in the east',
  },

  // West: forty divisions, second and third wave, no armour, little ammunition.
  {
    id: 'de-1-army',
    nation: 'germany',
    type: 'field',
    echelon: 'army',
    theater: 'west',
    zone: 'de-westwall',
    strength: { infantry: 240000, artillery: 900 },
    quality: 0.55,
    mobility: 0.25,
    source: '1st Army (Witzleben), the Saar sector of Army Group C',
  },
  {
    id: 'de-5-army',
    nation: 'germany',
    type: 'field',
    echelon: 'army',
    theater: 'west',
    zone: 'de-westwall',
    strength: { infantry: 190000, artillery: 700 },
    quality: 0.5,
    mobility: 0.25,
    source: '5th Army (Liebmann), the middle Rhine',
  },
  {
    id: 'de-7-army',
    nation: 'germany',
    type: 'field',
    echelon: 'army',
    theater: 'west',
    zone: 'de-westwall',
    strength: { infantry: 150000, artillery: 550 },
    quality: 0.5,
    mobility: 0.25,
    source: '7th Army (Dollmann), the upper Rhine',
  },
  {
    id: 'de-westwall-fortress',
    name: 'Westwall fortress troops',
    nation: 'germany',
    type: 'fortress',
    echelon: 'command',
    theater: 'west',
    zone: 'de-westwall',
    strength: { infantry: 120000, artillery: 900 },
    quality: 0.6,
    mobility: 0.05,
    source: 'Westwall fortress troops and border guards',
  },

  // The Luftwaffe. Two air fleets east, two west, and the eastern pair carry
  // about two thirds of everything that flies.
  {
    id: 'de-luftflotte-1a',
    name: 'Luftflotte 1 (East Prussia)',
    nation: 'germany',
    type: 'air',
    echelon: 'command',
    theater: 'east',
    sites: [[54.2, 20.5]],
    strength: { infantry: 9000, fighters: 160, bombers: 280 },
    quality: 0.9,
    mobility: 0.7,
    source: 'Luftflotte 1, East Prussian fields (Königsberg)',
  },
  {
    id: 'de-luftflotte-1b',
    name: 'Luftflotte 1 (Pomerania)',
    nation: 'germany',
    type: 'air',
    echelon: 'command',
    theater: 'east',
    sites: [[53.4, 15.6]],
    strength: { infantry: 8000, fighters: 140, bombers: 220 },
    quality: 0.9,
    mobility: 0.7,
    source: 'Luftflotte 1, Pomeranian fields (Stettin)',
  },
  {
    id: 'de-luftflotte-4a',
    name: 'Luftflotte 4 (Silesia)',
    nation: 'germany',
    type: 'air',
    echelon: 'command',
    theater: 'east',
    sites: [[50.9, 17.4]],
    strength: { infantry: 9000, fighters: 150, bombers: 250 },
    quality: 0.9,
    mobility: 0.7,
    source: 'Luftflotte 4, Silesian fields (Breslau)',
  },
  {
    id: 'de-luftflotte-4b',
    name: 'Luftflotte 4 (Moravia)',
    nation: 'germany',
    type: 'air',
    echelon: 'command',
    theater: 'east',
    sites: [[49.6, 18.3]],
    strength: { infantry: 7000, fighters: 100, bombers: 200 },
    quality: 0.85,
    mobility: 0.7,
    source: 'Luftflotte 4, Moravian and Slovak fields',
  },
  {
    id: 'de-luftflotte-2',
    nation: 'germany',
    type: 'air',
    echelon: 'command',
    theater: 'west',
    sites: [[51.96, 7.63]],
    strength: { infantry: 8000, fighters: 200, bombers: 300 },
    quality: 0.85,
    mobility: 0.7,
    source: 'Luftflotte 2, the lower Rhine',
  },
  {
    id: 'de-luftflotte-3',
    nation: 'germany',
    type: 'air',
    echelon: 'command',
    theater: 'west',
    sites: [[49.5, 8.5]],
    strength: { infantry: 7000, fighters: 200, bombers: 250 },
    quality: 0.85,
    mobility: 0.7,
    source: 'Luftflotte 3, the middle Rhine',
  },
  {
    id: 'de-training-air',
    name: 'Training and reserve units',
    nation: 'germany',
    type: 'air',
    echelon: 'command',
    theater: 'interior',
    sites: [[52.4, 12.6], [48.4, 11.7]],
    strength: { infantry: 6000, fighters: 150, bombers: 100 },
    quality: 0.4,
    mobility: 0.5,
    source: 'training and reserve units, Brandenburg and Bavaria',
  },

  // The interior: replacement army, flak, and nothing else. No field formation
  // is anywhere near Berlin on this date, which is the point.
  {
    id: 'de-ersatzheer',
    name: 'Ersatzheer',
    nation: 'germany',
    type: 'depot',
    echelon: 'command',
    theater: 'interior',
    // The Wehrkreis towns: Königsberg, Stettin, Berlin, Dresden, Stuttgart,
    // Münster, Munich, Breslau, Kassel, Hamburg, Hanover, Wiesbaden, Nuremberg,
    // Vienna.
    sites: [
      [54.7, 20.5, 0.6], [53.4, 14.6, 0.6], [52.5, 13.4, 1.0], [51.05, 13.7, 0.9],
      [48.8, 9.2, 0.9], [51.96, 7.6, 0.8], [48.14, 11.6, 1.0], [51.1, 17.0, 0.8],
      [51.3, 9.5, 0.7], [53.55, 10.0, 0.9], [52.4, 9.7, 0.7], [50.08, 8.24, 0.7],
      [49.45, 11.08, 0.7], [48.2, 16.4, 1.0],
    ],
    strength: { infantry: 700000, artillery: 600 },
    quality: 0.3,
    mobility: 0.1,
    source: 'Ersatzheer — replacement and training battalions in the Wehrkreise',
  },
  {
    id: 'de-flak',
    name: 'Luftwaffe Flak',
    nation: 'germany',
    type: 'aa',
    echelon: 'command',
    theater: 'interior',
    // The Ruhr first, and by a distance: the heaviest concentration of
    // anti-aircraft guns anywhere in the world in 1939.
    sites: [
      [51.45, 7.0, 3.0], [52.5, 13.4, 2.0], [53.55, 10.0, 1.2], [51.34, 12.4, 0.8],
      [48.2, 16.4, 0.8], [50.1, 8.7, 0.7], [49.45, 11.08, 0.5], [48.8, 9.2, 0.6],
      [51.05, 13.7, 0.5], [53.08, 8.8, 0.4],
    ],
    strength: { infantry: 180000, artillery: 5000 },
    quality: 0.7,
    mobility: 0.1,
    source: 'Luftwaffe Flak — the heaviest belts in the world, over the Ruhr',
  },
  {
    id: 'de-security',
    name: 'Ordnungspolizei',
    nation: 'germany',
    type: 'security',
    echelon: 'command',
    theater: 'interior',
    zone: 'de-interior',
    strength: { infantry: 100000, artillery: 100 },
    quality: 0.3,
    mobility: 0.2,
    source: 'Ordnungspolizei and rear-area troops, thin over the Reich',
  },

  // ==================================================================== //
  //                              POLAND                                  //
  // ==================================================================== //
  // A million men strung along two thousand kilometres of frontier, with
  // mobilisation about seventy per cent complete when it started.
  {
    id: 'pl-pomorze',
    nation: 'neutral',
    type: 'field',
    echelon: 'army',
    theater: 'poland',
    zone: 'pl-corridor',
    strength: { infantry: 110000, artillery: 320 },
    quality: 0.55,
    mobility: 0.25,
    source: 'Army Pomorze, in the Corridor and therefore already outflanked',
  },
  {
    id: 'pl-modlin',
    nation: 'neutral',
    type: 'field',
    echelon: 'army',
    theater: 'poland',
    zone: 'pl-corridor',
    strength: { infantry: 90000, artillery: 260 },
    quality: 0.55,
    mobility: 0.25,
    source: 'Army Modlin, facing East Prussia',
  },
  {
    id: 'pl-poznan',
    nation: 'neutral',
    type: 'field',
    echelon: 'army',
    theater: 'poland',
    zone: 'pl-west',
    strength: { infantry: 105000, artillery: 300 },
    quality: 0.6,
    mobility: 0.25,
    source: 'Army Poznań, holding the western salient',
  },
  {
    id: 'pl-lodz',
    nation: 'neutral',
    type: 'field',
    echelon: 'army',
    theater: 'poland',
    zone: 'pl-west',
    strength: { infantry: 100000, artillery: 290 },
    quality: 0.6,
    mobility: 0.25,
    source: 'Army Łódź, across the Warsaw axis',
  },
  {
    id: 'pl-krakow',
    nation: 'neutral',
    type: 'field',
    echelon: 'army',
    theater: 'poland',
    zone: 'pl-south',
    strength: { infantry: 150000, artillery: 420 },
    quality: 0.6,
    mobility: 0.25,
    source: 'Army Kraków, the strongest, on the Silesian industrial region',
  },
  {
    id: 'pl-karpaty',
    nation: 'neutral',
    type: 'field',
    echelon: 'army',
    theater: 'poland',
    zone: 'pl-south',
    strength: { infantry: 60000, artillery: 150 },
    quality: 0.45,
    mobility: 0.2,
    source: 'Army Karpaty, improvised on the Slovak frontier',
  },
  {
    id: 'pl-prusy',
    nation: 'neutral',
    type: 'field',
    echelon: 'army',
    theater: 'poland',
    zone: 'pl-reserve',
    strength: { infantry: 180000, artillery: 420 },
    quality: 0.55,
    mobility: 0.25,
    source: 'Army Prusy, the central reserve, still assembling on 1 September',
  },
  {
    id: 'pl-warszawa-armor',
    name: 'Warsaw Armoured Brigade',
    nation: 'neutral',
    type: 'armor',
    echelon: 'division',
    theater: 'poland',
    zone: 'pl-reserve',
    strength: { infantry: 6000, tanks: 90, artillery: 30 },
    quality: 0.6,
    mobility: 0.8,
    source: 'Warsaw Armoured Motorised Brigade',
  },
  {
    id: 'pl-10-cavalry',
    name: '10th Cavalry Brigade',
    nation: 'neutral',
    type: 'armor',
    echelon: 'division',
    theater: 'poland',
    zone: 'pl-south',
    strength: { infantry: 6000, tanks: 80, artillery: 30 },
    quality: 0.7,
    mobility: 0.8,
    source: '10th Motorised Cavalry Brigade (Maczek), the best in the army',
  },
  {
    id: 'pl-tankettes-north',
    name: 'Tankette companies, north',
    nation: 'neutral',
    type: 'armor',
    echelon: 'corps',
    theater: 'poland',
    zone: 'pl-corridor',
    strength: { infantry: 3000, tanks: 310 },
    quality: 0.3,
    mobility: 0.6,
    source: 'TKS and TK-3 tankette companies parcelled out to the northern armies',
  },
  {
    id: 'pl-tankettes-south',
    name: 'Tankettes and 7TPs, south',
    nation: 'neutral',
    type: 'armor',
    echelon: 'corps',
    theater: 'poland',
    zone: 'pl-south',
    strength: { infantry: 3000, tanks: 400 },
    quality: 0.3,
    mobility: 0.6,
    source: 'tankette companies and the 7TP battalions with Army Kraków',
  },
  {
    id: 'pl-air',
    name: 'Pursuit and Bomber Brigades',
    nation: 'neutral',
    type: 'air',
    echelon: 'command',
    theater: 'poland',
    // Dispersed to field strips before the attack, which is why the Luftwaffe
    // did not catch them on the ground.
    sites: [[52.2, 21.0], [51.55, 21.85], [49.84, 24.03]],
    strength: { infantry: 12000, fighters: 160, bombers: 120 },
    quality: 0.5,
    mobility: 0.7,
    source: 'Pursuit and Bomber Brigades on dispersal fields',
  },
  {
    id: 'pl-depot',
    name: 'Polish depots',
    nation: 'neutral',
    type: 'depot',
    echelon: 'command',
    theater: 'poland',
    sites: [[52.23, 21.0, 1.2], [50.06, 19.94, 0.8], [51.75, 19.46, 0.5], [52.4, 16.9, 0.6]],
    strength: { infantry: 90000, artillery: 120 },
    quality: 0.25,
    mobility: 0.1,
    source: 'depots and unmobilised reservists — mobilisation was ~70% complete',
  },

  // ==================================================================== //
  //                              FRANCE                                  //
  // ==================================================================== //
  {
    id: 'fr-maginot-fortress',
    nation: 'france',
    type: 'fortress',
    echelon: 'command',
    theater: 'northeast',
    zone: 'fr-maginot',
    strength: { infantry: 220000, artillery: 2200 },
    quality: 0.75,
    mobility: 0.02,
    source: 'Maginot fortress troops, Switzerland to Longuyon',
  },
  {
    id: 'fr-3-army',
    nation: 'france',
    type: 'field',
    echelon: 'army',
    theater: 'northeast',
    zone: 'fr-northeast',
    strength: { infantry: 280000, artillery: 1100 },
    quality: 0.7,
    mobility: 0.35,
    source: '3rd Army, behind the line at Metz',
  },
  {
    id: 'fr-4-army',
    nation: 'france',
    type: 'field',
    echelon: 'army',
    theater: 'northeast',
    zone: 'fr-northeast',
    strength: { infantry: 230000, artillery: 900 },
    quality: 0.7,
    mobility: 0.35,
    source: '4th Army, the Saar front',
  },
  {
    id: 'fr-5-army',
    nation: 'france',
    type: 'field',
    echelon: 'army',
    theater: 'northeast',
    zone: 'fr-maginot',
    strength: { infantry: 250000, artillery: 950 },
    quality: 0.7,
    mobility: 0.35,
    source: '5th Army, Alsace',
  },
  {
    id: 'fr-8-army',
    nation: 'france',
    type: 'field',
    echelon: 'army',
    theater: 'northeast',
    zone: 'fr-maginot',
    strength: { infantry: 180000, artillery: 700 },
    quality: 0.65,
    mobility: 0.3,
    source: '8th Army, the upper Rhine and the Swiss corner',
  },
  {
    id: 'fr-2-army',
    nation: 'france',
    type: 'field',
    echelon: 'army',
    theater: 'northeast',
    zone: 'fr-northeast',
    strength: { infantry: 200000, artillery: 800 },
    quality: 0.6,
    mobility: 0.3,
    source: '2nd Army, the Ardennes hinge at Sedan',
  },
  {
    id: 'fr-1-army',
    nation: 'france',
    type: 'field',
    echelon: 'army',
    theater: 'north',
    zone: 'fr-north',
    strength: { infantry: 300000, artillery: 1200 },
    quality: 0.8,
    mobility: 0.6,
    source: '1st Army, the best in France, opposite Belgium',
  },
  {
    id: 'fr-7-army',
    nation: 'france',
    type: 'field',
    echelon: 'army',
    theater: 'north',
    zone: 'fr-north',
    strength: { infantry: 220000, artillery: 850 },
    quality: 0.8,
    mobility: 0.65,
    source: '7th Army (Giraud), the far left, earmarked for Holland',
  },
  {
    id: 'fr-9-army',
    nation: 'france',
    type: 'field',
    echelon: 'army',
    theater: 'north',
    zone: 'fr-north',
    strength: { infantry: 190000, artillery: 700 },
    quality: 0.55,
    mobility: 0.4,
    source: '9th Army, holding the Ardennes sector thought impassable',
  },
  {
    id: 'fr-alps-army',
    nation: 'france',
    type: 'field',
    echelon: 'army',
    theater: 'alps',
    zone: 'fr-alps',
    strength: { infantry: 150000, artillery: 600 },
    quality: 0.7,
    mobility: 0.3,
    source: 'Army of the Alps, facing an Italy that has not declared',
  },
  // French armour, dispersed on purpose: independent battalions attached to
  // infantry corps rather than concentrated. Six placements against Germany's
  // fourteen, and the map should show the difference in shape as well as count.
  {
    id: 'fr-1-dlm',
    name: '1st DLM',
    nation: 'france',
    type: 'armor',
    echelon: 'division',
    theater: 'north',
    zone: 'fr-north',
    strength: { infantry: 11000, tanks: 260, artillery: 50 },
    quality: 0.8,
    mobility: 0.9,
    source: '1st Light Mechanised Division, 1st Army',
  },
  {
    id: 'fr-2-dlm',
    name: '2nd DLM',
    nation: 'france',
    type: 'armor',
    echelon: 'division',
    theater: 'north',
    zone: 'fr-north',
    strength: { infantry: 11000, tanks: 240, artillery: 50 },
    quality: 0.8,
    mobility: 0.9,
    source: '2nd Light Mechanised Division, 1st Army',
  },
  // The French tank park, and the argument France lost.
  //
  // Two and a half thousand tanks, more than Germany brought to Poland and
  // better armoured, parcelled out in independent battalions of forty-five to
  // support infantry corps. The Germans put theirs in six divisions. Both
  // decisions are visible on this map without a word of explanation: the same
  // number of machines, one side in fists and the other in fingers.
  {
    id: 'fr-tank-bns-3-army',
    name: 'Tank battalions, 3rd Army',
    nation: 'france',
    type: 'armor',
    echelon: 'corps',
    theater: 'northeast',
    zone: 'fr-northeast',
    strength: { infantry: 5000, tanks: 300, artillery: 20 },
    quality: 0.5,
    mobility: 0.45,
    source: 'independent tank battalions with the 3rd Army',
  },
  {
    id: 'fr-tank-bns-4-army',
    name: 'Tank battalions, 4th Army',
    nation: 'france',
    type: 'armor',
    echelon: 'corps',
    theater: 'northeast',
    zone: 'fr-northeast',
    strength: { infantry: 5000, tanks: 300, artillery: 20 },
    quality: 0.5,
    mobility: 0.45,
    source: 'independent tank battalions with the 4th Army',
  },
  {
    id: 'fr-tank-bns-2-army',
    name: 'Tank battalions, 2nd Army',
    nation: 'france',
    type: 'armor',
    echelon: 'corps',
    theater: 'northeast',
    zone: 'fr-northeast',
    strength: { infantry: 4000, tanks: 300, artillery: 20 },
    quality: 0.5,
    mobility: 0.45,
    source: 'independent tank battalions with the 2nd Army at Sedan',
  },
  {
    id: 'fr-tank-bns-1-army',
    name: 'Tank battalions, 1st Army',
    nation: 'france',
    type: 'armor',
    echelon: 'corps',
    theater: 'northeast',
    zone: 'fr-north',
    strength: { infantry: 4000, tanks: 280, artillery: 20 },
    quality: 0.5,
    mobility: 0.45,
    source: 'independent tank battalions with the 1st Army',
  },
  {
    id: 'fr-tank-bns-7-army',
    name: 'Tank battalions, 7th Army',
    nation: 'france',
    type: 'armor',
    echelon: 'corps',
    theater: 'northeast',
    zone: 'fr-north',
    strength: { infantry: 4000, tanks: 260, artillery: 20 },
    quality: 0.5,
    mobility: 0.45,
    source: 'independent tank battalions with the 7th Army',
  },
  {
    id: 'fr-tank-bns-9-army',
    name: 'Tank battalions, 9th Army',
    nation: 'france',
    type: 'armor',
    echelon: 'corps',
    theater: 'northeast',
    zone: 'fr-north',
    strength: { infantry: 4000, tanks: 240, artillery: 20 },
    quality: 0.5,
    mobility: 0.45,
    source: 'independent tank battalions with the 9th Army',
  },
  {
    id: 'fr-tank-bns-5-army',
    name: 'Tank battalions, 5th Army',
    nation: 'france',
    type: 'armor',
    echelon: 'corps',
    theater: 'northeast',
    zone: 'fr-maginot',
    strength: { infantry: 5000, tanks: 320, artillery: 20 },
    quality: 0.5,
    mobility: 0.45,
    source: 'infantry-support battalions behind the Alsace sectors',
  },
  {
    id: 'fr-tank-bns-8-army',
    name: 'Tank battalions, 8th Army',
    nation: 'france',
    type: 'armor',
    echelon: 'corps',
    theater: 'northeast',
    zone: 'fr-maginot',
    strength: { infantry: 5000, tanks: 300, artillery: 20 },
    quality: 0.5,
    mobility: 0.45,
    source: 'infantry-support battalions on the upper Rhine',
  },
  {
    id: 'fr-dcr-forming',
    name: 'The DCRs, forming',
    nation: 'france',
    type: 'armor',
    echelon: 'division',
    theater: 'interior',
    zone: 'fr-interior',
    strength: { infantry: 8000, tanks: 500, artillery: 40 },
    quality: 0.6,
    mobility: 0.7,
    source: 'the DCRs, still forming in the interior on this date',
  },
  {
    id: 'fr-air-northeast',
    name: 'ZOA Nord and Est',
    nation: 'france',
    type: 'air',
    echelon: 'command',
    theater: 'northeast',
    sites: [[48.7, 6.2], [49.3, 4.0]],
    strength: { infantry: 14000, fighters: 520, bombers: 320 },
    quality: 0.6,
    mobility: 0.7,
    source: "Zone d'Opérations Aériennes Nord and Est",
  },
  {
    id: 'fr-air-south',
    name: 'ZOA Sud and North Africa',
    nation: 'france',
    type: 'air',
    echelon: 'command',
    theater: 'interior',
    sites: [[43.6, 5.0], [36.8, 3.1]],
    strength: { infantry: 8000, fighters: 280, bombers: 280 },
    quality: 0.5,
    mobility: 0.7,
    source: 'southern zone and North African fields',
  },
  {
    id: 'fr-19-corps',
    name: '19th Corps, North Africa',
    nation: 'france',
    type: 'field',
    echelon: 'corps',
    theater: 'africa',
    zone: 'fr-africa',
    strength: { infantry: 190000, artillery: 500 },
    quality: 0.6,
    mobility: 0.3,
    source: '19th Corps, Algeria, Morocco and Tunisia',
  },
  {
    id: 'fr-levant-army',
    name: 'Army of the Levant',
    nation: 'france',
    type: 'field',
    echelon: 'corps',
    theater: 'levant',
    zone: 'fr-levant',
    strength: { infantry: 90000, artillery: 220 },
    quality: 0.55,
    mobility: 0.3,
    source: 'Army of the Levant, Syria and Lebanon',
  },
  {
    id: 'fr-indochina-army',
    name: 'Indochina garrison',
    nation: 'france',
    type: 'field',
    echelon: 'corps',
    theater: 'far-east',
    zone: 'fr-indochina',
    strength: { infantry: 50000, artillery: 120 },
    quality: 0.45,
    mobility: 0.2,
    source: 'the Indochina garrison, largely colonial troops',
  },
  {
    id: 'fr-depot',
    name: 'French depots',
    nation: 'france',
    type: 'depot',
    echelon: 'command',
    theater: 'interior',
    sites: [
      [48.86, 2.35, 1.4], [45.76, 4.84, 0.8], [43.3, 5.4, 0.7], [43.6, 1.44, 0.6],
      [44.84, -0.58, 0.6], [47.22, -1.55, 0.5], [48.11, -1.68, 0.5], [45.19, 5.72, 0.4],
    ],
    strength: { infantry: 420000, artillery: 400 },
    quality: 0.3,
    mobility: 0.1,
    source: 'depots of the military regions — general mobilisation ordered today',
  },
  {
    id: 'fr-aa',
    name: 'DCA',
    nation: 'france',
    type: 'aa',
    echelon: 'command',
    theater: 'interior',
    sites: [[48.86, 2.35, 2.0], [50.63, 3.06, 0.8], [45.76, 4.84, 0.7], [49.26, 4.03, 0.5]],
    strength: { infantry: 60000, artillery: 700 },
    quality: 0.5,
    mobility: 0.1,
    source: 'DCA over Paris and the northern industrial towns',
  },
  {
    id: 'fr-security',
    name: 'Garde Republicaine Mobile',
    nation: 'france',
    type: 'security',
    echelon: 'command',
    theater: 'interior',
    zone: 'fr-interior',
    strength: { infantry: 80000, artillery: 60 },
    quality: 0.3,
    mobility: 0.2,
    source: 'Garde Républicaine Mobile and rear-area troops',
  },

  // ==================================================================== //
  //                        THE UNITED KINGDOM                            //
  // ==================================================================== //
  {
    id: 'uk-bef',
    nation: 'uk',
    type: 'field',
    echelon: 'corps',
    theater: 'home',
    // Still in southern England on 1 September: the first divisions do not
    // cross until the 4th. On day 0 the BEF is a port, not a front.
    sites: [[51.05, -1.3, 1.0], [50.9, -1.4, 1.0], [51.3, 1.1, 0.8]],
    strength: { infantry: 152000, artillery: 350 },
    quality: 0.8,
    mobility: 0.7,
    source: 'the BEF, four divisions, embarking in the southern ports',
  },
  {
    id: 'uk-home-forces',
    name: 'Territorials and training',
    nation: 'uk',
    type: 'depot',
    echelon: 'command',
    theater: 'home',
    sites: [
      [51.5, -0.1, 1.0], [53.5, -2.2, 0.7], [55.9, -3.2, 0.5], [52.5, -1.9, 0.6],
      [51.06, -1.79, 0.6], [54.97, -1.6, 0.4], [51.45, -2.6, 0.4],
    ],
    strength: { infantry: 180000, artillery: 200 },
    quality: 0.35,
    mobility: 0.2,
    source: 'Territorial divisions and training establishments at home',
  },
  {
    id: 'uk-aa-command',
    name: 'AA Command',
    nation: 'uk',
    type: 'aa',
    echelon: 'command',
    theater: 'home',
    // London and the Thames estuary first, then the Midlands works.
    sites: [
      [51.5, -0.1, 3.0], [51.5, 0.7, 1.0], [52.48, -1.9, 1.2], [53.48, -2.24, 1.0],
      [53.8, -1.55, 0.6], [55.86, -4.25, 0.7], [54.97, -1.6, 0.5], [50.8, -1.1, 0.6],
    ],
    strength: { infantry: 96000, artillery: 700 },
    quality: 0.6,
    mobility: 0.1,
    source: 'AA Command — the heaviest gun belt in Europe after the Ruhr',
  },
  {
    id: 'uk-fighter-command',
    nation: 'uk',
    type: 'air',
    echelon: 'command',
    theater: 'home',
    // Sector stations of 11 and 12 Group, south-east and east.
    sites: [[51.3, 0.06], [51.6, -0.4], [52.1, 0.5], [53.0, -0.8]],
    strength: { infantry: 26000, fighters: 600, bombers: 0 },
    quality: 0.85,
    mobility: 0.8,
    source: 'Fighter Command, ~600 aircraft on sector airfields',
  },
  {
    id: 'uk-bomber-command',
    nation: 'uk',
    type: 'air',
    echelon: 'command',
    theater: 'home',
    // East Anglia and Lincolnshire, where the bomber fields were and are.
    sites: [[52.4, 0.6], [53.2, -0.5], [52.9, -0.1]],
    strength: { infantry: 22000, fighters: 0, bombers: 480 },
    quality: 0.7,
    mobility: 0.8,
    source: 'Bomber Command, East Anglia and Lincolnshire',
  },
  {
    id: 'uk-india-army',
    name: 'Indian Army',
    nation: 'uk',
    type: 'field',
    echelon: 'command',
    theater: 'india',
    // The Indian Army: the largest ground force in the Empire, and on this
    // date the only large one.
    sites: [
      [28.6, 77.2, 1.0], [31.6, 74.3, 1.2], [33.4, 74.8, 0.8], [34.0, 71.5, 1.0],
      [19.08, 72.88, 0.6], [22.57, 88.36, 0.6], [13.08, 80.27, 0.5], [30.3, 78.0, 0.5],
    ],
    strength: { infantry: 205000, artillery: 260 },
    quality: 0.6,
    mobility: 0.3,
    source: 'Indian Army, ~200k, with the frontier commands on the North-West',
  },
  {
    id: 'uk-middle-east-command',
    name: 'Middle East Command',
    nation: 'uk',
    type: 'field',
    echelon: 'command',
    theater: 'middle-east',
    // Egypt and Iraq are sovereign on this date; the garrisons are there by
    // treaty, which is the whole quarrel.
    foreign: true,
    sites: [[30.05, 31.24, 1.4], [31.2, 29.9, 0.8], [31.78, 35.22, 1.0], [32.5, 44.4, 0.5]],
    strength: { infantry: 86000, artillery: 220 },
    quality: 0.75,
    mobility: 0.6,
    source: 'Middle East Command — Egypt, and Palestine still heavy after the revolt',
  },
  {
    id: 'uk-far-east-command',
    name: 'Malaya and Hong Kong',
    nation: 'uk',
    type: 'field',
    echelon: 'command',
    theater: 'far-east',
    sites: [[1.29, 103.85, 1.4], [3.14, 101.69, 0.6], [22.3, 114.17, 0.7], [16.8, 96.15, 0.4]],
    strength: { infantry: 42000, tanks: 0, artillery: 120 },
    quality: 0.5,
    mobility: 0.3,
    source: 'Malaya Command, Singapore fortress, Hong Kong and Burma',
  },
  {
    id: 'uk-africa-garrisons',
    name: 'African garrisons',
    nation: 'uk',
    type: 'field',
    echelon: 'command',
    theater: 'africa',
    sites: [[15.5, 32.53, 0.8], [-1.29, 36.82, 0.6], [12.78, 45.03, 0.4], [6.5, 3.4, 0.4], [-26.2, 28.0, 0.6]],
    strength: { infantry: 48000, artillery: 90 },
    quality: 0.45,
    mobility: 0.25,
    source: 'Sudan Defence Force, King’s African Rifles, West African Frontier Force',
  },
  {
    id: 'uk-fortress-garrisons',
    name: 'Fortress garrisons',
    // Gibraltar and Aden are smaller than a 67 km hex, so those two garrisons
    // are placed on the nearest land the board has — which for Gibraltar is
    // Spain. They are fed by sea from ground the map cannot give them, so they
    // are marked as standing on somebody else's soil, which is exactly what
    // they are doing.
    //
    // Malta used to be in the same position and was deployed onto Sicily. It is
    // not any more: Malta was one of the islands stamped onto the board when
    // the Mediterranean and the Pacific turned out to be missing most of their
    // rocks, and the garrison went to it without a line here changing.
    foreign: true,
    nation: 'uk',
    type: 'fortress',
    echelon: 'command',
    theater: 'imperial',
    sites: [[36.13, -5.35, 1.0], [35.9, 14.5, 1.0], [12.78, 45.03, 0.6]],
    strength: { infantry: 21000, artillery: 160 },
    quality: 0.7,
    mobility: 0.05,
    source: 'Gibraltar, Malta and Aden fortress garrisons',
  },
  {
    id: 'uk-dominion-forces',
    name: 'Dominion forces',
    nation: 'uk',
    type: 'depot',
    echelon: 'command',
    theater: 'dominions',
    sites: [
      [45.4, -75.7, 0.8], [43.65, -79.4, 0.6], [-33.87, 151.2, 0.8], [-37.8, 144.96, 0.6],
      [-41.3, 174.8, 0.4], [-33.9, 18.4, 0.5],
    ],
    strength: { infantry: 92000, artillery: 90 },
    quality: 0.5,
    mobility: 0.3,
    source: 'Dominion forces mobilising — none of them overseas yet on this date',
  },
  {
    id: 'uk-security',
    name: 'Colonial police',
    nation: 'uk',
    type: 'security',
    echelon: 'command',
    theater: 'imperial',
    zone: 'uk-africa',
    strength: { infantry: 30000, artillery: 30 },
    quality: 0.3,
    mobility: 0.2,
    source: 'colonial police and internal security detachments',
  },
  {
    id: 'uk-imperial-air',
    name: 'RAF overseas commands',
    nation: 'uk',
    type: 'air',
    echelon: 'command',
    theater: 'imperial',
    sites: [[30.05, 31.24], [1.29, 103.85], [28.6, 77.2]],
    strength: { infantry: 14000, fighters: 150, bombers: 70 },
    quality: 0.5,
    mobility: 0.7,
    source: 'RAF Middle East, Far East and India commands',
  },

  // ==================================================================== //
  //                       THE SOVIET UNION                               //
  // ==================================================================== //
  // The nation a population smear damages most: 4,589 cells of ground, and
  // almost all of the army in three corners of it.
  {
    id: 'su-belorussian-front',
    name: 'Belorussian district',
    nation: 'ussr',
    type: 'field',
    echelon: 'command',
    theater: 'west',
    zone: 'su-belorussia',
    strength: { infantry: 380000, artillery: 5200 },
    quality: 0.5,
    mobility: 0.4,
    source: 'Belorussian Special Military District, massing for 17 September',
  },
  {
    id: 'su-kiev-front',
    name: 'Kiev district',
    nation: 'ussr',
    type: 'field',
    echelon: 'command',
    theater: 'west',
    zone: 'su-kiev',
    strength: { infantry: 420000, artillery: 5800 },
    quality: 0.5,
    mobility: 0.4,
    source: 'Kiev Special Military District, the larger of the two',
  },
  {
    id: 'su-belorussian-armor',
    name: 'Belorussian tank corps',
    nation: 'ussr',
    type: 'armor',
    echelon: 'corps',
    theater: 'west',
    zone: 'su-belorussia',
    strength: { infantry: 40000, tanks: 3200, artillery: 400 },
    quality: 0.45,
    mobility: 0.8,
    source: 'tank corps and brigades of the Belorussian district — T-26 and BT',
  },
  {
    id: 'su-kiev-armor',
    name: 'Kiev tank corps',
    nation: 'ussr',
    type: 'armor',
    echelon: 'corps',
    theater: 'west',
    zone: 'su-kiev',
    strength: { infantry: 45000, tanks: 3800, artillery: 450 },
    quality: 0.45,
    mobility: 0.8,
    source: 'tank corps and brigades of the Kiev district',
  },
  {
    id: 'su-leningrad-district',
    name: 'Leningrad district',
    nation: 'ussr',
    type: 'field',
    echelon: 'command',
    theater: 'north',
    zone: 'su-leningrad',
    strength: { infantry: 200000, artillery: 3000 },
    quality: 0.45,
    mobility: 0.35,
    source: 'Leningrad Military District, building towards the Finnish frontier',
  },
  {
    id: 'su-leningrad-armor',
    name: 'Leningrad tank brigades',
    nation: 'ussr',
    type: 'armor',
    echelon: 'corps',
    theater: 'north',
    zone: 'su-leningrad',
    strength: { infantry: 20000, tanks: 1600, artillery: 200 },
    quality: 0.45,
    mobility: 0.75,
    source: 'tank brigades of the Leningrad district',
  },
  {
    id: 'su-far-eastern-front',
    nation: 'ussr',
    type: 'field',
    echelon: 'command',
    theater: 'far-east',
    zone: 'su-far-east',
    strength: { infantry: 320000, artillery: 4200 },
    quality: 0.55,
    mobility: 0.35,
    source: 'Far Eastern Front — the Amur, the Ussuri and Vladivostok',
  },
  {
    id: 'su-transbaikal-front',
    nation: 'ussr',
    type: 'field',
    echelon: 'command',
    theater: 'far-east',
    zone: 'su-transbaikal',
    strength: { infantry: 240000, artillery: 3400 },
    quality: 0.55,
    mobility: 0.4,
    source: 'Transbaikal Front, and 1st Army Group fighting at Khalkhin Gol today',
  },
  {
    id: 'su-far-east-armor',
    name: "Zhukov's armoured brigades",
    nation: 'ussr',
    type: 'armor',
    echelon: 'corps',
    theater: 'far-east',
    zone: 'su-transbaikal',
    strength: { infantry: 45000, tanks: 3600, artillery: 500 },
    quality: 0.55,
    mobility: 0.8,
    source: 'Zhukov’s armoured brigades — the concentration that won Nomonhan',
  },
  {
    id: 'su-far-east-armor-2',
    name: 'Far Eastern tank brigades',
    nation: 'ussr',
    type: 'armor',
    echelon: 'corps',
    theater: 'far-east',
    zone: 'su-far-east',
    strength: { infantry: 35000, tanks: 2600, artillery: 380 },
    quality: 0.5,
    mobility: 0.75,
    source: 'tank brigades of the Far Eastern Front',
  },
  {
    id: 'su-interior-armor',
    name: 'Reserve tank parks',
    nation: 'ussr',
    type: 'armor',
    echelon: 'corps',
    theater: 'interior',
    sites: [[55.75, 37.6], [50.0, 36.2], [48.5, 44.5]],
    strength: { infantry: 40000, tanks: 6200, artillery: 600 },
    quality: 0.35,
    mobility: 0.6,
    source: 'training and reserve tank parks — the bulk of 21,000 hulls was not at a front',
  },
  {
    id: 'su-air-west',
    name: 'VVS, western districts',
    nation: 'ussr',
    type: 'air',
    echelon: 'command',
    theater: 'west',
    sites: [[53.9, 27.6], [50.45, 30.5], [49.8, 24.0]],
    strength: { infantry: 40000, fighters: 1600, bombers: 1300 },
    quality: 0.45,
    mobility: 0.6,
    source: 'VVS of the western districts',
  },
  {
    id: 'su-air-east',
    name: 'VVS, Far East',
    nation: 'ussr',
    type: 'air',
    echelon: 'command',
    theater: 'far-east',
    sites: [[43.1, 131.9], [51.8, 107.6]],
    strength: { infantry: 30000, fighters: 1100, bombers: 900 },
    quality: 0.5,
    mobility: 0.6,
    source: 'VVS of the Far East, reinforced for Khalkhin Gol',
  },
  {
    id: 'su-air-interior',
    name: 'VVS, interior',
    nation: 'ussr',
    type: 'air',
    echelon: 'command',
    theater: 'interior',
    sites: [[55.75, 37.6], [59.9, 30.3], [56.3, 44.0]],
    strength: { infantry: 30000, fighters: 1300, bombers: 1300 },
    quality: 0.35,
    mobility: 0.5,
    source: 'interior districts, training regiments and the long-range force',
  },
  {
    id: 'su-depot',
    name: 'Interior districts',
    nation: 'ussr',
    type: 'depot',
    echelon: 'command',
    theater: 'interior',
    sites: [
      [55.75, 37.6, 1.6], [59.93, 30.34, 1.0], [56.3, 44.0, 0.6], [55.0, 82.9, 0.5],
      [56.84, 60.6, 0.6], [51.5, 46.0, 0.4], [47.2, 39.7, 0.4], [43.0, 74.6, 0.3],
      [41.3, 69.3, 0.3], [55.03, 73.4, 0.3],
    ],
    strength: { infantry: 380000, artillery: 3600 },
    quality: 0.3,
    mobility: 0.1,
    source: 'interior military districts — cadre and replacement only',
  },
  {
    id: 'su-security',
    name: 'NKVD troops',
    nation: 'ussr',
    type: 'security',
    echelon: 'command',
    theater: 'interior',
    zone: 'su-interior',
    strength: { infantry: 130000, artillery: 400 },
    quality: 0.4,
    mobility: 0.3,
    source: 'NKVD border and internal troops',
  },
  {
    id: 'su-aa',
    name: 'PVO',
    nation: 'ussr',
    type: 'aa',
    echelon: 'command',
    theater: 'interior',
    sites: [[55.75, 37.6, 2.0], [59.93, 30.34, 1.4], [48.5, 39.3, 0.8], [53.2, 50.15, 0.5]],
    strength: { infantry: 100000, artillery: 2800 },
    quality: 0.4,
    mobility: 0.1,
    source: 'PVO over Moscow, Leningrad and the Donbas',
  },

  // ==================================================================== //
  //                               ITALY                                  //
  // ==================================================================== //
  {
    id: 'it-1-army',
    nation: 'italy',
    type: 'field',
    echelon: 'army',
    theater: 'home',
    zone: 'it-alps',
    strength: { infantry: 280000, artillery: 1300 },
    quality: 0.5,
    mobility: 0.3,
    source: '1st Army, the French frontier — non-belligerent on this date',
  },
  {
    id: 'it-2-army',
    nation: 'italy',
    type: 'field',
    echelon: 'army',
    theater: 'home',
    zone: 'it-east',
    strength: { infantry: 200000, artillery: 900 },
    quality: 0.5,
    mobility: 0.3,
    source: '2nd Army, the Yugoslav frontier',
  },
  {
    id: 'it-po-reserve',
    name: 'Po valley reserve',
    nation: 'italy',
    type: 'field',
    echelon: 'corps',
    theater: 'home',
    zone: 'it-home',
    strength: { infantry: 240000, artillery: 1100 },
    quality: 0.45,
    mobility: 0.3,
    source: 'the Po valley reserve corps',
  },
  {
    id: 'it-armor',
    name: 'Armoured and Celere divisions',
    nation: 'italy',
    type: 'armor',
    echelon: 'division',
    theater: 'home',
    zone: 'it-home',
    strength: { infantry: 14000, tanks: 900, artillery: 60 },
    quality: 0.25,
    mobility: 0.6,
    // Nearly all of it is the L3, a two-man machine-gun carrier that was
    // obsolete when it was built. The count says 900; the quality says what
    // they were worth.
    source: 'armoured and Celere divisions — overwhelmingly L3 tankettes',
  },
  {
    id: 'it-libya-army',
    name: "Balbo's command",
    nation: 'italy',
    type: 'field',
    echelon: 'command',
    theater: 'libya',
    // Tripoli, Benghazi, Tobruk, Derna, Misrata, Sirte, Sebha, Ajdabiya.
    sites: [
      [32.9, 13.19, 1.4], [32.12, 20.07, 1.0], [32.08, 23.98, 0.8], [32.77, 22.64, 0.6],
      [32.38, 15.09, 0.5], [31.2, 16.59, 0.4], [27.04, 14.43, 0.3], [30.75, 20.22, 0.3],
    ],
    strength: { infantry: 220000, artillery: 700 },
    quality: 0.4,
    mobility: 0.3,
    source: 'Balbo’s command in Libya — Tripolitania and Cyrenaica',
  },
  {
    id: 'it-east-africa-army',
    name: 'Italian East Africa',
    nation: 'italy',
    type: 'field',
    echelon: 'command',
    theater: 'east-africa',
    // Addis Ababa, Asmara, Mogadishu, Harar, Gondar, Jimma, Massawa and the
    // Somali posts. A quarter of a million men, and most of them Eritrean.
    sites: [
      [9.03, 38.74, 1.4], [15.34, 38.93, 1.1], [2.05, 45.32, 0.7], [9.31, 42.12, 0.6],
      [12.6, 37.47, 0.6], [7.67, 36.83, 0.5], [15.61, 39.45, 0.5], [5.35, 43.65, 0.4],
      [9.35, 42.79, 0.4], [11.13, 39.63, 0.4], [-0.36, 42.55, 0.3],
    ],
    strength: { infantry: 290000, artillery: 900 },
    quality: 0.3,
    mobility: 0.2,
    source: 'the Duke of Aosta’s command — largely colonial troops',
  },
  {
    id: 'it-albania-corps',
    name: 'Albanian occupation corps',
    nation: 'italy',
    type: 'field',
    echelon: 'corps',
    theater: 'balkans',
    sites: [[41.33, 19.82, 1.2], [41.32, 19.45, 0.9], [40.47, 19.49, 0.8], [42.07, 19.51, 0.6]],
    strength: { infantry: 100000, artillery: 300 },
    quality: 0.45,
    mobility: 0.3,
    source: 'the Albanian occupation corps, ashore since April',
  },
  {
    id: 'it-air',
    name: 'Regia Aeronautica',
    nation: 'italy',
    type: 'air',
    echelon: 'command',
    theater: 'home',
    sites: [[45.5, 9.2], [41.8, 12.6], [40.9, 14.3], [32.9, 13.2]],
    strength: { infantry: 30000, fighters: 800, bombers: 800 },
    quality: 0.45,
    mobility: 0.6,
    source: 'Regia Aeronautica — the peninsula and Libya',
  },
  {
    id: 'it-depot',
    name: 'Italian depots',
    nation: 'italy',
    type: 'depot',
    echelon: 'command',
    theater: 'home',
    sites: [[41.9, 12.5, 1.2], [45.46, 9.19, 1.0], [40.85, 14.27, 0.8], [45.07, 7.69, 0.7], [38.1, 13.4, 0.5]],
    strength: { infantry: 180000, artillery: 500 },
    quality: 0.25,
    mobility: 0.1,
    source: 'depot divisions and the Fascist militia at home',
  },
  {
    id: 'it-aa',
    name: 'DICAT',
    nation: 'italy',
    type: 'aa',
    echelon: 'command',
    theater: 'home',
    sites: [[45.46, 9.19, 1.4], [45.07, 7.69, 1.0], [44.4, 8.95, 0.9], [41.9, 12.5, 0.8]],
    strength: { infantry: 40000, artillery: 700 },
    quality: 0.4,
    mobility: 0.1,
    source: 'DICAT over the northern industrial triangle',
  },
  {
    id: 'it-security',
    name: 'Carabinieri',
    nation: 'italy',
    type: 'security',
    echelon: 'command',
    theater: 'home',
    zone: 'it-home',
    strength: { infantry: 36000, artillery: 40 },
    quality: 0.3,
    mobility: 0.2,
    source: 'Carabinieri and rear-area troops',
  },

  // ==================================================================== //
  //                               JAPAN                                  //
  // ==================================================================== //
  // Fifty-one divisions and almost none of them at home. In China the army
  // holds cities, ports and the railways between them, and nothing else.
  {
    id: 'jp-north-china-army',
    name: 'North China Area Army',
    nation: 'japan',
    type: 'field',
    echelon: 'command',
    theater: 'china',
    zone: 'jp-north-china',
    strength: { infantry: 340000, artillery: 1000 },
    quality: 0.8,
    mobility: 0.45,
    source: 'North China Area Army — Beijing, Tianjin and the rail corridors',
  },
  {
    id: 'jp-central-china-army',
    name: 'Central China Army',
    nation: 'japan',
    type: 'field',
    echelon: 'command',
    theater: 'china',
    zone: 'jp-central-china',
    strength: { infantry: 380000, artillery: 1100 },
    quality: 0.8,
    mobility: 0.45,
    source: 'Central China Expeditionary Army — Shanghai, Nanjing, Wuhan',
  },
  {
    id: 'jp-south-china-army',
    nation: 'japan',
    type: 'field',
    echelon: 'command',
    theater: 'china',
    zone: 'jp-south-china',
    strength: { infantry: 140000, artillery: 420 },
    quality: 0.75,
    mobility: 0.45,
    source: '21st Army, Guangzhou and the Pearl River delta',
  },
  {
    id: 'jp-kwantung-army',
    nation: 'japan',
    type: 'field',
    echelon: 'command',
    theater: 'manchuria',
    zone: 'jp-manchuria',
    strength: { infantry: 300000, artillery: 1200 },
    quality: 0.85,
    mobility: 0.5,
    source: 'the Kwantung Army, ~9 divisions, engaged at Nomonhan today',
  },
  {
    id: 'jp-korea-army',
    nation: 'japan',
    type: 'field',
    echelon: 'command',
    theater: 'korea',
    zone: 'jp-korea',
    strength: { infantry: 70000, artillery: 200 },
    quality: 0.7,
    mobility: 0.4,
    source: 'the Korea Army, two divisions',
  },
  {
    id: 'jp-china-armor',
    name: 'Tank regiments, central China',
    nation: 'japan',
    type: 'armor',
    echelon: 'corps',
    theater: 'china',
    zone: 'jp-central-china',
    strength: { infantry: 12000, tanks: 620, artillery: 60 },
    quality: 0.7,
    mobility: 0.8,
    source: 'independent tank regiments in central China',
  },
  {
    id: 'jp-manchuria-armor',
    name: 'Kwantung tank regiments',
    nation: 'japan',
    type: 'armor',
    echelon: 'corps',
    theater: 'manchuria',
    zone: 'jp-manchuria',
    strength: { infantry: 14000, tanks: 1030, artillery: 80 },
    quality: 0.75,
    mobility: 0.85,
    source: 'the Kwantung Army’s tank regiments, mauled at Nomonhan',
  },
  {
    id: 'jp-air-china',
    name: 'Air groups in China',
    nation: 'japan',
    type: 'air',
    echelon: 'command',
    theater: 'china',
    sites: [[31.23, 121.47], [30.6, 114.3], [39.9, 116.4], [23.1, 113.3]],
    strength: { infantry: 26000, fighters: 500, bombers: 480 },
    quality: 0.8,
    mobility: 0.7,
    source: 'army air groups on Chinese fields',
  },
  {
    id: 'jp-air-manchuria',
    name: '2nd Air Group',
    nation: 'japan',
    type: 'air',
    echelon: 'command',
    theater: 'manchuria',
    sites: [[43.9, 125.3], [45.8, 126.6]],
    strength: { infantry: 14000, fighters: 320, bombers: 200 },
    quality: 0.8,
    mobility: 0.7,
    source: 'the 2nd Air Group, Manchuria',
  },
  {
    id: 'jp-air-home',
    name: 'Home defence air groups',
    nation: 'japan',
    type: 'air',
    echelon: 'command',
    theater: 'home',
    sites: [[35.7, 139.7], [34.7, 135.5]],
    strength: { infantry: 12000, fighters: 380, bombers: 320 },
    quality: 0.7,
    mobility: 0.7,
    source: 'home defence and training groups',
  },
  {
    id: 'jp-home-depot',
    name: 'Home depot divisions',
    nation: 'japan',
    type: 'depot',
    echelon: 'command',
    theater: 'home',
    sites: [
      [35.7, 139.7, 1.2], [34.69, 135.5, 1.0], [35.18, 136.9, 0.7], [33.59, 130.4, 0.7],
      [34.4, 132.5, 0.6], [43.06, 141.35, 0.5], [38.27, 140.87, 0.5],
    ],
    strength: { infantry: 300000, artillery: 700 },
    quality: 0.5,
    mobility: 0.2,
    source: 'depot divisions of the home military districts',
  },
  {
    id: 'jp-china-security',
    name: 'Railway guards',
    nation: 'japan',
    type: 'security',
    echelon: 'command',
    theater: 'china',
    zone: 'jp-north-china',
    strength: { infantry: 130000, artillery: 200 },
    quality: 0.4,
    mobility: 0.3,
    source: 'railway guards and garrison units strung along the corridors',
  },
  {
    id: 'jp-aa',
    name: 'Home anti-aircraft',
    nation: 'japan',
    type: 'aa',
    echelon: 'command',
    theater: 'home',
    sites: [[35.7, 139.7, 1.6], [34.69, 135.5, 1.0], [33.59, 130.4, 0.6], [34.4, 132.5, 0.6]],
    strength: { infantry: 30000, artillery: 340 },
    quality: 0.45,
    mobility: 0.1,
    source: 'home anti-aircraft over Tokyo, Osaka and the naval towns',
  },

  // ==================================================================== //
  //                               CHINA                                  //
  // ==================================================================== //
  // Three million men in three hundred nominal divisions, most of them
  // without artillery, transport or boots. The count is the largest army on
  // the board; the quality says what that was worth.
  {
    id: 'cn-north-zones',
    name: '1st and 2nd War Zones',
    nation: 'china',
    type: 'field',
    echelon: 'command',
    theater: 'china',
    zone: 'cn-north-front',
    strength: { infantry: 600000, artillery: 180 },
    quality: 0.25,
    mobility: 0.15,
    source: '1st and 2nd War Zones — Shanxi and the Yellow River',
  },
  {
    id: 'cn-central-zones',
    name: '5th and 9th War Zones',
    nation: 'china',
    type: 'field',
    echelon: 'command',
    theater: 'china',
    zone: 'cn-central-front',
    strength: { infantry: 780000, artillery: 260 },
    quality: 0.3,
    mobility: 0.15,
    source: '5th and 9th War Zones — Hubei and Hunan, and Changsha opening now',
  },
  {
    id: 'cn-south-zones',
    name: '4th and 7th War Zones',
    nation: 'china',
    type: 'field',
    echelon: 'command',
    theater: 'china',
    zone: 'cn-south-front',
    strength: { infantry: 420000, artillery: 120 },
    quality: 0.25,
    mobility: 0.15,
    source: '4th and 7th War Zones — Guangxi and the south',
  },
  {
    id: 'cn-8th-route',
    name: '8th Route Army',
    nation: 'china',
    type: 'field',
    echelon: 'command',
    theater: 'china',
    // Yan'an and the mountain bases. Three of these are inside the Japanese
    // occupation and are supposed to be: that is what the army was for.
    foreign: true,
    sites: [
      [36.6, 109.49, 1.4], [38.02, 113.39, 0.8], [35.5, 113.0, 0.7],
      [37.52, 111.13, 0.7], [34.27, 108.95, 0.5],
    ],
    strength: { infantry: 220000, artillery: 20 },
    quality: 0.35,
    mobility: 0.5,
    // A separate force in everything but name, fighting a different war in the
    // same theatre. It is given its own zone for that reason.
    source: 'the Communist 8th Route Army in Shaanxi and Shanxi',
  },
  {
    id: 'cn-rear-armies',
    name: 'Sichuan armies',
    nation: 'china',
    type: 'field',
    echelon: 'command',
    theater: 'china',
    zone: 'cn-rear',
    strength: { infantry: 300000, artillery: 140 },
    quality: 0.3,
    mobility: 0.15,
    source: 'the Sichuan armies and the strategic reserve behind Chongqing',
  },
  {
    id: 'cn-armor',
    name: '200th Division',
    nation: 'china',
    type: 'armor',
    echelon: 'division',
    theater: 'china',
    zone: 'cn-rear',
    strength: { infantry: 4000, tanks: 100, artillery: 20 },
    quality: 0.3,
    mobility: 0.6,
    source: 'the 200th Division — the only mechanised formation in China',
  },
  {
    id: 'cn-air',
    name: 'Chinese Air Force',
    nation: 'china',
    type: 'air',
    echelon: 'command',
    theater: 'china',
    sites: [[29.56, 106.55], [30.66, 104.06], [25.04, 102.7]],
    strength: { infantry: 16000, fighters: 200, bombers: 100 },
    quality: 0.3,
    mobility: 0.6,
    source: 'the Chinese Air Force and the Soviet volunteer group',
  },
  {
    id: 'cn-depot',
    name: 'Chinese training divisions',
    nation: 'china',
    type: 'depot',
    echelon: 'command',
    theater: 'china',
    sites: [[29.56, 106.55, 1.4], [30.66, 104.06, 1.0], [25.04, 102.7, 0.6], [34.27, 108.95, 0.6]],
    strength: { infantry: 160000, artillery: 40 },
    quality: 0.2,
    mobility: 0.1,
    source: 'training divisions in the Sichuan and Yunnan rear',
  },

  // ==================================================================== //
  //                       THE UNITED STATES                              //
  // ==================================================================== //
  // Nineteenth in the world. Nine partially manned divisions in the whole
  // continental United States, and an interior that is genuinely empty.
  {
    id: 'us-continental-posts',
    name: 'The continental posts',
    nation: 'usa',
    type: 'field',
    echelon: 'command',
    theater: 'continental',
    sites: [
      [32.35, -84.97, 1.0], [29.45, -98.44, 0.9], [47.1, -122.58, 0.7],
      [39.05, -96.8, 0.6], [35.14, -79.0, 0.6], [38.9, -77.0, 0.5], [42.4, -71.1, 0.4],
    ],
    strength: { infantry: 96000, artillery: 380 },
    quality: 0.55,
    mobility: 0.5,
    source: 'Benning, Sam Houston, Lewis, Riley, Bragg — divisions at half strength',
  },
  {
    id: 'us-national-guard',
    name: 'National Guard',
    nation: 'usa',
    type: 'depot',
    echelon: 'command',
    theater: 'continental',
    sites: [
      [40.7, -74.0, 1.0], [41.88, -87.63, 0.9], [34.05, -118.24, 0.7], [32.78, -96.8, 0.6],
      [39.95, -75.17, 0.6], [42.33, -83.05, 0.5], [33.75, -84.39, 0.5], [44.98, -93.27, 0.4],
    ],
    strength: { infantry: 190000, artillery: 180 },
    quality: 0.3,
    mobility: 0.2,
    source: 'National Guard armouries — 200,000 men, drilling, not embodied',
  },
  {
    id: 'us-overseas-departments',
    name: 'Overseas departments',
    nation: 'usa',
    type: 'field',
    echelon: 'command',
    theater: 'overseas',
    // The last of these is the 4th Marines in the Shanghai settlement, which
    // is Japanese-occupied ground and is meant to be.
    foreign: true,
    sites: [
      [9.0, -79.6, 1.2], [21.35, -157.95, 1.2], [14.6, 120.98, 1.0],
      [18.4, -66.1, 0.4], [31.23, 121.47, 0.3],
    ],
    strength: { infantry: 38000, artillery: 200 },
    quality: 0.6,
    mobility: 0.4,
    source: 'Panama, Hawaii, the Philippine Department, Puerto Rico, 4th Marines',
  },
  {
    id: 'us-air-corps',
    name: 'Air Corps',
    nation: 'usa',
    type: 'air',
    echelon: 'command',
    theater: 'continental',
    sites: [[38.0, -122.0], [39.8, -84.05], [29.4, -98.5], [21.35, -157.95]],
    strength: { infantry: 26000, fighters: 800, bombers: 500 },
    quality: 0.55,
    mobility: 0.7,
    source: 'the Air Corps — ~2,400 aircraft, of which ~800 first line',
  },
  {
    id: 'us-coast-artillery',
    name: 'Coast Artillery',
    nation: 'usa',
    type: 'aa',
    echelon: 'command',
    theater: 'continental',
    sites: [[40.7, -74.0, 1.0], [37.8, -122.4, 0.8], [9.0, -79.6, 0.8], [21.35, -157.95, 0.7]],
    strength: { infantry: 22000, artillery: 220 },
    quality: 0.5,
    mobility: 0.1,
    source: 'Coast Artillery Corps, harbour defences and anti-aircraft',
  },

  // ==================================================================== //
  //                         THE MINOR POWERS                             //
  // ==================================================================== //
  {
    id: 'be-field-army',
    nation: 'neutral',
    type: 'field',
    echelon: 'command',
    theater: 'low-countries',
    zone: 'be-frontier',
    strength: { infantry: 550000, artillery: 1200 },
    quality: 0.5,
    mobility: 0.3,
    source: 'the Belgian army, mobilised on its own frontier since 25 August',
  },
  {
    id: 'nl-field-army',
    name: 'Dutch field army',
    nation: 'neutral',
    type: 'field',
    echelon: 'command',
    theater: 'low-countries',
    zone: 'nl-frontier',
    strength: { infantry: 270000, artillery: 650 },
    quality: 0.4,
    mobility: 0.25,
    source: 'the Dutch army behind the water line, mobilised 28 August',
  },
  {
    id: 'fi-army',
    name: 'Finnish army',
    nation: 'neutral',
    type: 'field',
    echelon: 'command',
    theater: 'scandinavia',
    zone: 'fi-karelia',
    strength: { infantry: 300000, artillery: 700 },
    quality: 0.7,
    mobility: 0.4,
    source: 'the Finnish army on the Karelian Isthmus — the Winter War is 90 days away',
  },
  {
    id: 'ro-army',
    nation: 'neutral',
    type: 'field',
    echelon: 'command',
    theater: 'balkans',
    zone: 'ro-frontier',
    strength: { infantry: 900000, artillery: 1600 },
    quality: 0.4,
    mobility: 0.25,
    source: 'the Romanian army, mobilised on the Soviet and Hungarian frontiers',
  },
  {
    id: 'hu-army',
    nation: 'neutral',
    type: 'field',
    echelon: 'command',
    theater: 'balkans',
    zone: 'hu-frontier',
    strength: { infantry: 200000, artillery: 500 },
    quality: 0.45,
    mobility: 0.3,
    source: 'the Hungarian army — a German co-belligerent in all but signature',
  },
  {
    id: 'yu-army',
    nation: 'neutral',
    type: 'field',
    echelon: 'command',
    theater: 'balkans',
    zone: 'yu-frontier',
    strength: { infantry: 500000, artillery: 1100 },
    quality: 0.35,
    mobility: 0.2,
    source: 'the Royal Yugoslav Army',
  },
  {
    id: 'gr-army',
    nation: 'neutral',
    type: 'field',
    echelon: 'command',
    theater: 'balkans',
    zone: 'gr-frontier',
    strength: { infantry: 160000, artillery: 400 },
    quality: 0.5,
    mobility: 0.2,
    source: 'the Greek army, watching Italian Albania',
  },
  {
    id: 'tr-army',
    nation: 'neutral',
    type: 'field',
    echelon: 'command',
    theater: 'near-east',
    zone: 'tr-thrace',
    strength: { infantry: 600000, artillery: 1300 },
    quality: 0.45,
    mobility: 0.2,
    source: 'the Turkish army, weighted to Thrace and the Straits',
  },
  {
    id: 'es-army',
    name: 'Spanish army',
    nation: 'neutral',
    type: 'field',
    echelon: 'command',
    theater: 'iberia',
    zone: 'es-home',
    strength: { infantry: 500000, artillery: 800 },
    quality: 0.4,
    mobility: 0.2,
    source: 'the Spanish army five months after the civil war, demobilising',
  },
  {
    id: 'se-army',
    nation: 'neutral',
    type: 'field',
    echelon: 'command',
    theater: 'scandinavia',
    zone: 'se-home',
    strength: { infantry: 110000, artillery: 300 },
    quality: 0.5,
    mobility: 0.3,
    source: 'the Swedish army, partially called up',
  },
  {
    id: 'ch-army',
    name: 'Swiss army',
    nation: 'neutral',
    type: 'field',
    echelon: 'command',
    theater: 'alps',
    zone: 'ch-redoubt',
    strength: { infantry: 430000, artillery: 900 },
    quality: 0.6,
    mobility: 0.3,
    source: 'general mobilisation of 28 August — the frontier and the redoubt',
  },
  {
    id: 'neutral-rest-armies',
    name: 'The other neutral armies',
    nation: 'neutral',
    type: 'security',
    echelon: 'command',
    theater: 'world',
    // Denmark, Norway, Portugal, Ireland, Iran, Afghanistan, Thailand, and the
    // Americas. Everyone with an army and no part in what is about to happen.
    sites: [
      [55.68, 12.57, 0.8], [59.91, 10.75, 0.7], [38.72, -9.14, 0.7], [53.35, -6.26, 0.4],
      [35.7, 51.42, 1.0], [34.53, 69.17, 0.6], [13.75, 100.5, 0.7], [-22.9, -43.17, 0.9],
      [-34.6, -58.38, 0.9], [19.43, -99.13, 0.8], [4.71, -74.07, 0.5], [-12.05, -77.04, 0.5],
      [-33.45, -70.67, 0.5], [4.6, -74.1, 0.3],
    ],
    strength: { infantry: 180000, artillery: 350 },
    quality: 0.3,
    mobility: 0.2,
    source: 'every other neutral army, from Denmark to Argentina, pooled',
  },
  {
    id: 'neutral-air',
    name: 'The neutral air forces',
    nation: 'neutral',
    type: 'air',
    echelon: 'command',
    theater: 'world',
    sites: [
      [50.85, 4.35], [52.37, 4.9], [60.17, 24.94], [44.43, 26.1],
      [44.8, 20.47], [39.93, 32.86], [40.42, -3.7], [46.95, 7.45], [59.33, 18.07],
    ],
    strength: { infantry: 30000, fighters: 740, bombers: 380 },
    quality: 0.4,
    mobility: 0.6,
    source: 'the air forces of the neutrals, each on its own fields',
  },

  // ==================================================================== //
  //                    ARMOUR OF THE SMALLER ARMIES                      //
  // ==================================================================== //
  // Every tank on the board belongs to a formation of its own. None is an
  // attachment to a corps of riflemen, because none of them were: armour in
  // 1939 came in battalions and brigades that stood somewhere particular, and
  // a map that dusts a nation's tanks over its infantry is telling a lie about
  // both. It is also what makes the count testable — a hex with tanks on it
  // holds a whole formation's worth or it holds none.
  {
    id: 'uk-home-armor',
    name: 'RTR battalions at home',
    nation: 'uk',
    type: 'armor',
    echelon: 'corps',
    theater: 'home',
    sites: [[50.7, -2.2, 1.0], [51.25, -0.77, 0.8]],
    strength: { infantry: 9000, tanks: 880, artillery: 40 },
    quality: 0.6,
    mobility: 0.85,
    source: 'Royal Tank Regiment battalions and the training parks at home',
  },
  {
    id: 'uk-india-armor',
    name: 'Indian armoured cars',
    nation: 'uk',
    type: 'armor',
    echelon: 'corps',
    theater: 'india',
    sites: [[31.6, 74.3]],
    strength: { infantry: 3000, tanks: 60, artillery: 10 },
    quality: 0.45,
    mobility: 0.8,
    source: 'Indian armoured car and light tank companies',
  },
  {
    id: 'uk-egypt-armor',
    name: 'Mobile Division (Egypt)',
    nation: 'uk',
    type: 'armor',
    echelon: 'division',
    theater: 'middle-east',
    sites: [[30.05, 31.24]],
    strength: { infantry: 8000, tanks: 180, artillery: 40 },
    quality: 0.75,
    mobility: 0.9,
    source: 'the Mobile Division (Egypt), later 7th Armoured',
  },
  {
    id: 'uk-dominion-armor',
    name: 'Dominion armour',
    nation: 'uk',
    type: 'armor',
    echelon: 'corps',
    theater: 'dominions',
    sites: [[45.4, -75.7]],
    strength: { infantry: 1500, tanks: 30, artillery: 5 },
    quality: 0.4,
    mobility: 0.8,
    source: 'Dominion armoured units, barely formed',
  },
  {
    id: 'us-knox-armor',
    name: '7th Cavalry (Mechanized)',
    nation: 'usa',
    type: 'armor',
    echelon: 'division',
    theater: 'continental',
    sites: [[37.9, -85.95]],
    strength: { infantry: 5000, tanks: 300, artillery: 30 },
    quality: 0.6,
    mobility: 0.9,
    source: '7th Cavalry Brigade (Mechanized) at Fort Knox',
  },
  {
    id: 'us-overseas-armor',
    name: 'Overseas tank companies',
    nation: 'usa',
    type: 'armor',
    echelon: 'corps',
    theater: 'overseas',
    sites: [[9.0, -79.6, 1.0], [14.6, 120.98, 1.0]],
    strength: { infantry: 2000, tanks: 100, artillery: 15 },
    quality: 0.55,
    mobility: 0.8,
    source: 'tank companies in Panama and the Philippines',
  },
  {
    id: 'it-libya-armor',
    name: 'Libyan tank battalions',
    nation: 'italy',
    type: 'armor',
    echelon: 'corps',
    theater: 'libya',
    sites: [[32.9, 13.19, 1.0], [32.12, 20.07, 0.8]],
    strength: { infantry: 6000, tanks: 300, artillery: 30 },
    quality: 0.25,
    mobility: 0.7,
    source: 'the Libyan tank battalions, L3 tankettes almost to a man',
  },
  {
    id: 'it-east-africa-armor',
    name: 'East African tankettes',
    nation: 'italy',
    type: 'armor',
    echelon: 'corps',
    theater: 'east-africa',
    sites: [[9.03, 38.74, 1.0], [15.34, 38.93, 0.8]],
    strength: { infantry: 2500, tanks: 60, artillery: 10 },
    quality: 0.2,
    mobility: 0.6,
    source: 'a handful of tankettes and armoured cars in East Africa',
  },
  {
    id: 'it-albania-armor',
    name: 'Albanian tank battalion',
    nation: 'italy',
    type: 'armor',
    echelon: 'corps',
    theater: 'balkans',
    sites: [[41.33, 19.82]],
    strength: { infantry: 2500, tanks: 60, artillery: 10 },
    quality: 0.3,
    mobility: 0.7,
    source: 'the Albanian tank battalion',
  },
  {
    id: 'jp-north-china-armor',
    name: 'Tank regiments, north China',
    nation: 'japan',
    type: 'armor',
    echelon: 'corps',
    theater: 'china',
    zone: 'jp-north-china',
    strength: { infantry: 8000, tanks: 260, artillery: 40 },
    quality: 0.7,
    mobility: 0.8,
    source: 'independent tank regiments in north China',
  },
  {
    id: 'jp-south-china-armor',
    name: 'Tank company, 21st Army',
    nation: 'japan',
    type: 'armor',
    echelon: 'corps',
    theater: 'china',
    zone: 'jp-south-china',
    strength: { infantry: 4000, tanks: 90, artillery: 20 },
    quality: 0.7,
    mobility: 0.8,
    source: 'the tank company with 21st Army at Guangzhou',
  },
  {
    id: 'be-armor',
    name: 'Belgian T-13s',
    nation: 'neutral',
    type: 'armor',
    echelon: 'corps',
    theater: 'low-countries',
    zone: 'be-frontier',
    strength: { infantry: 6000, tanks: 270, artillery: 30 },
    quality: 0.45,
    mobility: 0.75,
    source: 'Belgian T-13 tank destroyers and the Cyclist Corps',
  },
  {
    id: 'nl-armor',
    name: 'Dutch armour',
    nation: 'neutral',
    type: 'armor',
    echelon: 'corps',
    theater: 'low-countries',
    zone: 'nl-frontier',
    strength: { infantry: 800, tanks: 5, artillery: 5 },
    quality: 0.3,
    mobility: 0.7,
    source: 'the entire Dutch armoured force: five vehicles',
  },
  {
    id: 'fi-armor',
    name: 'Finnish tank battalion',
    nation: 'neutral',
    type: 'armor',
    echelon: 'corps',
    theater: 'scandinavia',
    zone: 'fi-karelia',
    strength: { infantry: 1200, tanks: 30, artillery: 5 },
    quality: 0.5,
    mobility: 0.7,
    source: 'the Finnish tank battalion, Renault FTs of the last war',
  },
  {
    id: 'ro-armor',
    name: '1st Romanian Armoured',
    nation: 'neutral',
    type: 'armor',
    echelon: 'division',
    theater: 'balkans',
    zone: 'ro-frontier',
    strength: { infantry: 7000, tanks: 250, artillery: 30 },
    quality: 0.4,
    mobility: 0.7,
    source: 'the Romanian 1st Armoured, on Czech R-2 tanks',
  },
  {
    id: 'hu-armor',
    name: 'Hungarian mechanised brigades',
    nation: 'neutral',
    type: 'armor',
    echelon: 'corps',
    theater: 'balkans',
    zone: 'hu-frontier',
    strength: { infantry: 4000, tanks: 130, artillery: 20 },
    quality: 0.45,
    mobility: 0.75,
    source: 'the Hungarian mechanised brigades, Ansaldo tankettes',
  },
  {
    id: 'yu-armor',
    name: 'Yugoslav tank battalions',
    nation: 'neutral',
    type: 'armor',
    echelon: 'corps',
    theater: 'balkans',
    zone: 'yu-frontier',
    strength: { infantry: 3000, tanks: 110, artillery: 15 },
    quality: 0.3,
    mobility: 0.6,
    source: 'the Yugoslav tank battalions, Renault FTs and R35s',
  },
  {
    id: 'tr-armor',
    name: 'Turkish armoured brigade',
    nation: 'neutral',
    type: 'armor',
    echelon: 'corps',
    theater: 'near-east',
    zone: 'tr-thrace',
    strength: { infantry: 3000, tanks: 100, artillery: 15 },
    quality: 0.4,
    mobility: 0.7,
    source: 'the Turkish armoured brigade at Ankara',
  },
  {
    id: 'es-armor',
    name: 'Spanish armour',
    nation: 'neutral',
    type: 'armor',
    echelon: 'corps',
    theater: 'iberia',
    zone: 'es-home',
    strength: { infantry: 4000, tanks: 150, artillery: 20 },
    quality: 0.45,
    mobility: 0.7,
    source: 'Spanish tanks, German and Soviet, captured from each other',
  },
  {
    id: 'se-armor',
    name: 'Swedish armoured battalion',
    nation: 'neutral',
    type: 'armor',
    echelon: 'corps',
    theater: 'scandinavia',
    zone: 'se-home',
    strength: { infantry: 1500, tanks: 50, artillery: 10 },
    quality: 0.5,
    mobility: 0.75,
    source: 'the Swedish armoured battalion',
  },
  {
    id: 'ch-armor',
    name: 'Swiss light tanks',
    nation: 'neutral',
    type: 'armor',
    echelon: 'corps',
    theater: 'alps',
    zone: 'ch-redoubt',
    strength: { infantry: 800, tanks: 24, artillery: 5 },
    quality: 0.5,
    mobility: 0.6,
    source: 'twenty-four Swiss light tanks, and no more were coming',
  },
  {
    id: 'neutral-rest-armor',
    name: 'Neutral armour, pooled',
    nation: 'neutral',
    type: 'armor',
    echelon: 'corps',
    theater: 'world',
    sites: [[55.68, 12.57], [-34.6, -58.4], [-23.5, -46.6]],
    strength: { infantry: 2000, tanks: 60, artillery: 20 },
    quality: 0.3,
    mobility: 0.6,
    source: 'the armour of every other neutral, pooled',
  },
  // ------------------------------------------------- the island stations
  //
  // Fifty islands went onto the board when the Pacific turned out to be empty
  // water, and the order of battle had nothing to say about any of them,
  // because when it was written they did not exist.
  //
  // What goes on them is small, and deliberately so. **Most of these places
  // were held by a district officer and a police sergeant.** Wake had Pan
  // American Airways and a construction gang; the Marine detachment did not
  // arrive until August 1941. The Aleutians had nothing at all — Dutch Harbor
  // was not begun until 1940, and Attu had forty-five Aleuts and a
  // schoolteacher. The Japanese mandate was forbidden fortification by the
  // treaty it was held under, and the fortifying began in 1940.
  //
  // So the empty islands stay empty. That is not an omission. It is why a
  // battalion could take one, and why the Pacific war looked the way it did.
  {
    id: 'uk-island-stations',
    name: 'Island stations',
    nation: 'uk',
    type: 'security',
    echelon: 'command',
    theater: 'imperial',
    // Colombo, Suva, Bermuda, Kingston, Port Louis, Stanley.
    sites: [
      [6.93, 79.86, 1.0],
      [-18.14, 178.44, 0.5],
      [32.3, -64.75, 0.4],
      [17.97, -76.79, 0.5],
      [-20.16, 57.5, 0.25],
      [-51.7, -57.85, 0.1],
    ],
    strength: { infantry: 8300, artillery: 40 },
    quality: 0.4,
    mobility: 0.15,
    source: 'the Ceylon, Fiji, Bermuda, Jamaica, Mauritius and Falklands defence forces',
  },
  {
    id: 'uk-pacific-mandate',
    name: 'The Pacific mandate',
    nation: 'uk',
    type: 'security',
    echelon: 'division',
    theater: 'far-east',
    // Rabaul, Port Moresby, Tulagi. The New Guinea Volunteer Rifles were about
    // five hundred men across a territory the size of Spain, and the British
    // Solomons were administered from Tulagi by a resident commissioner with a
    // constabulary. Two years later this is where the war was.
    sites: [[-4.4, 152.1, 1.0], [-9.44, 147.18, 0.8], [-9.1, 160.15, 0.3]],
    strength: { infantry: 1400, artillery: 4 },
    quality: 0.3,
    mobility: 0.2,
    source: 'the New Guinea Volunteer Rifles and the Solomons constabulary',
  },
  {
    id: 'us-pacific-outposts',
    name: 'Pacific outposts',
    nation: 'usa',
    type: 'security',
    echelon: 'division',
    theater: 'pacific',
    // Guam, Midway, Pago Pago. Guam had 153 Marines and 247 men of the Insular
    // Force Guard, and the Naval Act of 1939 had just refused to fortify it on
    // the grounds that doing so would provoke Japan. It fell in two days.
    sites: [[13.45, 144.75, 1.0], [28.2, -177.37, 0.4], [-14.28, -170.7, 0.9]],
    strength: { infantry: 980, artillery: 8 },
    quality: 0.5,
    mobility: 0.1,
    source: 'the Guam, Midway and Samoa naval stations',
  },
  {
    id: 'fr-pacific-garrisons',
    name: 'Pacific colonial troops',
    nation: 'france',
    type: 'security',
    echelon: 'division',
    theater: 'imperial',
    // Noumea and Papeete.
    sites: [[-22.28, 166.46, 1.0], [-17.53, -149.57, 0.3]],
    strength: { infantry: 1300, artillery: 4 },
    quality: 0.35,
    mobility: 0.2,
    source: 'the New Caledonia and Tahiti colonial garrisons',
  },
  {
    id: 'jp-mandate-garrison',
    name: 'The South Seas mandate',
    nation: 'japan',
    type: 'security',
    echelon: 'division',
    theater: 'pacific',
    // Truk, Saipan, Palau, Kwajalein, Okinawa. Deliberately tiny: the Class C
    // mandate Japan held these under forbade fortification, and the surveys
    // that led to the airfields and the coast guns did not begin until 1940.
    // In September 1939 the 4th Fleet was setting up house at Truk and there
    // was almost nothing behind it.
    sites: [
      [7.42, 151.78, 1.0],
      [15.2, 145.75, 0.7],
      [7.5, 134.55, 0.6],
      [9.2, 167.48, 0.3],
      [26.33, 127.8, 1.2],
    ],
    strength: { infantry: 3500, artillery: 20 },
    quality: 0.5,
    mobility: 0.15,
    source: 'the 4th Fleet base staff and the Okinawa garrison',
  },
  {
    id: 'nl-east-indies',
    name: 'The Netherlands East Indies army',
    nation: 'neutral',
    type: 'field',
    echelon: 'command',
    theater: 'far-east',
    // Batavia, Surabaya, Medan, Balikpapan, Ambon. The KNIL was a colonial army
    // of about 35,000, most of it Javanese and Ambonese, and it was the only
    // thing standing between the oil of Sumatra and Borneo and anybody who
    // wanted it. Its absence from the board was the largest hole left in the
    // Far East once the East Indies became somewhere worth taking.
    sites: [
      [-6.2, 106.85, 1.0],
      [-7.25, 112.75, 0.8],
      [3.6, 98.67, 0.5],
      [-1.24, 116.83, 0.3],
      [-3.7, 128.18, 0.3],
    ],
    strength: { infantry: 35000, artillery: 120 },
    quality: 0.35,
    mobility: 0.3,
    source: 'the Koninklijk Nederlandsch-Indisch Leger',
  },
];
